esphome:
  name: 1
  friendly_name: 1

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "Li+u6RDwDox4Yx1Jm3ms6OPUsWlhpQ1kv/XWuGh8bmw="

ota:
  password: "746e882aa200cff7de3c6b1a522b8ce5"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "1 Fallback Hotspot"
    password: "W4Zra3j4joBU"

captive_portal:
    