esphome:
  name: 2
  friendly_name: 2

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "dZt/wsVeCXNkswtl7n9RDXuAA+55Wru4Qd0Zy/XnmE0="

ota:
  password: "a09cd8cfe33ed80da87f9798bb81e179"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "2 Fallback Hotspot"
    password: "8OKDwrZ3TjKv"

captive_portal:
    