esphome:
  name: 2
  friendly_name: 2

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "Dus/fdxzC7os6533br5dKMVwAhKWNnc5EJdD5DQuuOQ="

ota:
  password: "18537c239dc2c9cf6b3b6e58dfc17b6f"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "2 Fallback Hotspot"
    password: "rmG3PQ9LE5fo"

captive_portal:
    