esphome:
  name: qq
  friendly_name: qq

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "FRALjPNK6tFtu2hfGQCG2JvONmIBuwKWySb/Sckt0Vw="

ota:
  password: "02ae91a394bc04b7bece998b0ab66342"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Qq Fallback Hotspot"
    password: "O2fHTiLWLKJP"

captive_portal:
    