esphome:
  name: t
  friendly_name: t

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "jUp938BHqS7iMvI52PSuRSyz9ROb1vu5ZmRKqTmz9yE="

ota:
  password: "e2cd0156ac018741005e0da5822d9831"

safe_mode:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "T Fallback Hotspot"
    password: "QVXruiySibrB"

captive_portal:
    