substitutions:
  device_ssid: "Spare Light"
  device_name: sparebathroomlight
  device_description: "CWWW 36W Starry PMMA Square Ceiling LED light"
  friendly_name: "Spare Bathroom Light"    # Put the name that you want to see in Home Assistant.
  main_device_id: "sparebathroomlight"    # Put the name that you want to see in Home Assistant.
  tradfri_topic: ashishswitch-/button/1/command
  project_name: "lusunt.36w-cct-starry-pmmma-ceiling-light-square-esp-12f"
  project_version: "1.0"

# Enable Home Assistant API
api:
  encryption:
    key: !secret spare_bathroom_noise_key
  reboot_timeout: 0s

<<: !include .base-debug.yaml
<<: !include .base.device.light.lusunt-26w-esp12f.yaml
<<: !include .base.automation.light-mqtt-tradfri.yaml
<<: !include .base.common-binary-sensor.yaml
<<: !include .base.common-sensor.yaml
<<: !include .base.common-button.yaml
<<: !include .base.common-text-sensor.yaml