  # Device Specific Config
  esphome:
    name: ${device_name}
    comment: ${device_description}
    platformio_options:
      board_build.f_cpu: 160000000L
    project:
      name: "${project_name}"
      version: "${project_version}"

  esp32:
    board: esp32doit-devkit-v1
    framework:
      type: esp-idf
      sdkconfig_options:
        CONFIG_FREERTOS_UNICORE: y
        CONFIG_ESP32_DEFAULT_CPU_FREQ_160: y
        CONFIG_ESP32_DEFAULT_CPU_FREQ_MHZ: "160"

  external_components:
    - source: github://pr#4330
      components: [internal_temperature]
      refresh: always
    - source: github://pr#3500
    # - source: github://dentra/esphome@web-server-idf
      components:
        - web_server
        - web_server_idf
        - web_server_base
        - captive_portal
      refresh: 100days

#  captive_portal:

  web_server:
#    port: 80
#    auth:
#      username: admin
#      password: !secret web_server_password
#    include_internal: true
#    local: true

  # http_request:
  #   useragent: esphome/device
  #   timeout: 10s