mqtt:
  broker: !secret mqtt_ip
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: false
  birth_message:
    topic: ${name}/status
    payload: online
  will_message:
    topic: ${name}/status
    payload: offline
  skip_cert_cn_check: true
  idf_send_async: true
  certificate_authority: | >
    -----BEGIN CERTIFICATE-----
    MIIDjzCCAnegAwIBAgIUCCL7c2D9m3Yh6K9IfNWfBaq1vHAwDQYJKoZIhvcNAQEL
    BQAwVzELMAkGA1UEBhMCQ0ExCzAJBgNVBAgMAkFCMQ4wDAYDVQQHDAVMZWR1YzEQ
    MA4GA1UECgwHbWUuaG9tZTEZMBcGA1UEAwwQaGFzcy5mcmVpdGVyLm5ldDAeFw0y
    MjA2MDYxNzA3MzlaFw0zMjA2MDMxNzA3MzlaMFcxCzAJBgNVBAYTAkNBMQswCQYD
    VQQIDAJBQjEOMAwGA1UEBwwFTGVkdWMxEDAOBgNVBAoMB21lLmhvbWUxGTAXBgNV
    BAMMEGhhc3MuZnJlaXRlci5uZXQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
    AoIBAQDVu0hziYV/r3YAw89sO6zwUdKOjAmE7vFE1R/0KySbd
    JhQJdOb5zNOfBmO54e5qrAZ195rl/rX/2pjemdyLHwFBWzUiK0tlRWlaIanRAnmi
    GcWcZNMOLo+i6nTJc0ArA4pPbWYbA9vMKf1GuGFQhoRxQS4NMcveugAPSVLRk/m4
    aWyy
    -----END CERTIFICATE-----