switch: 
  - platform: "tuya"
    id: "${main_device_id}_mode"
    name: "${friendly_name} Switch Mode"
    switch_datapoint: 102
  # - platform: "tuya"
  #   id: "${main_device_id}_test"
  #   name: "${friendly_name} Tuya Test"
  #   switch_datapoint: 104