mqtt:
  broker: !secret mqtt_ip
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true
  on_message:
    - topic: $lonsonho1_topic
      payload: 'SHORT_CLICK'
      qos: 0
      then:
        - light.toggle: ${main_device_id}_light
    - topic: $lonsonho2_topic
      payload: 'SHORT_CLICK'
      qos: 0
      then:
        - fan.toggle: ${main_device_id}_fan