# Device Specific Config
esphome:
  name: ${device_name}
  # name_add_mac_suffix: true
  comment: ${device_description}
  platform: ESP8266
  board: esp_wroom_02
  project:
    name: "${project_name}"
    version: "${project_version}"

captive_portal:

web_server:
  port: 80
  auth:
    username: admin
    password: !secret web_server_password
  include_internal: true
  # local: true

uart:
  - id: mcu
    rx_pin: RX
    tx_pin: TX
    # baud_rate: 9600
    baud_rate: 115200
    debug:
      direction: BOTH
      dummy_receiver: false
      after:
        delimiter: "\n"
      sequence:
        - lambda: UARTDebug::log_hex(direction, bytes, ':');
  # - id: mcu2
  #   rx_pin: RX
  #   tx_pin: TX
  #   baud_rate: 9600
  #   debug:
  #     direction: BOTH
  #     dummy_receiver: false
  #     after:
  #       delimiter: "\n"
  #     sequence:
  #       - lambda: UARTDebug::log_hex(direction, bytes, ':');

# Register the Tuya MCU connection
tuya:
  uart_id: mcu

light:
  - platform: "tuya"
    name: "${friendly_name}"
    id: ${main_device_id}
    dimmer_datapoint: 22
    switch_datapoint: 20
    report_datapoint: 22
    report_datapoint: 22
    # min_value_datapoint: 26
    # color_temperature_datapoint: 23
    # color_temperature_max_value: 1000
    # color_temperature_invert: true
    min_value: 25
    max_value: 1000
    # cold_white_color_temperature: 153 mireds
    # warm_white_color_temperature: 500 mireds
    icon: "${dimmer_icon}"
# Datapoint 20: switch (value: ON)
# Datapoint 21: enum (value: 0)
# Datapoint 22: int value (value: 878)
# Datapoint 26: int value (value: 0)
# Product: '{"p":"vhqbpwy6a5ke1nig","
# Backlog TuyaMCU 11,20; TuyaMCU 98,21; TuyaMCU 21,22; TuyaMCU 23,23; TuyaMCU 99,24; TuyaMCU 12,34; DimmerRange 10,1000
# cmd/tas Switch/Relay#; enum#########; Dimmer#######; CCT##########; String#######; String#######; DimmerMinMax