mqtt:
  broker: !secret mqtt_ip
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: false
  on_message:
    - topic: $lonsonho_topic
      payload: 'SHORT_CLICK'
      qos: 0
      then:
        - fan.toggle: ${main_device_id}_fan
    # on_message:
    # - topic: bedford/ota_mode
    #   payload: 'ON'
    #   then:
    #     - deep_sleep.prevent: deep_sleep_1
    # - topic: bedford/sleep_mode
    #   payload: 'ON'
    #   then:
    #     - deep_sleep.enter: deep_sleep_1