esphome:
  name: "${device_name}"
  # name_add_mac_suffix: true
  comment: ${device_description}
  project:
    name: "${project_name}"
    version: "${project_version}"

esp32:
  board: esp32dev
  variant: esp32
  framework: 
    type: arduino
    version: 2.0.9
    platform_version: 6.3.0

external_components:
  # - source:
  #     type: local
  #     path: my_external_components/test9
#       # path: .external_components/shelly_new_fixing_issues_original_dallas
#       path: .external_components/shelly_new_fixing_issues
  # - source:
  #     type: local
  #     path: my_external_components/test10
  # - source: github://nrandell/dallasng

captive_portal:

web_server:
  port: 80
  auth:
    username: admin
    password: !secret web_server_password
  include_internal: true
  local: true

# dallas:
#   input_pin: GPIO3
#   output_pin: GPIO0

# shelly_dallas_new:
#   pin_a: GPIO3
#   pin_b: GPIO0

dallas:
  pin: GPIO19

# dallasng:
#   pin: 19
#   update_interval: 3s
