esphome:
  name: "${name}"
  # name_add_mac_suffix: true
  comment: ${device_description}
  platform: ESP8266
  board: esp01_1m
  project:
    name: "${project_name}"
    version: "${project_version}"

captive_portal:

web_server:
  port: 80
  auth:
    username: admin
    password: !secret web_server_password
  include_internal: true
  local: true

# globals:
#   - id: last_light_on
#     type: int
#     restore_value: no
#     initial_value: '1'

# Device Specific Config
output:
  - platform: gpio
    pin: GPIO4
    id: shelly_1_relay

light:
  - platform: binary
    name: "${friendly_name}"
    output: shelly_1_relay
    id: ${device_id_white}
    icon: ${light_icon}