# this provides for a possibility to restart from the web console or Home automation should we ever need it
button:
  - platform: restart
    id: "restart_device"
    name: "${friendly_name} Restart"
    entity_category: 'diagnostic'
  - platform: safe_mode
    id: "restart_device_safe_mode"
    name: "${friendly_name} Restart (Safe Mode)"
    entity_category: 'diagnostic'