binary_sensor:
  - platform: status
    name: "${friendly_name} Status"
  - platform: gpio
    name: "${friendly_name} Button 1"
    pin:
      number: GPIO12
      mode:
        input: true
    on_multi_click:
      # double click
      - timing:
          - ON for at most 1s
          - OFF for at most 1s
          - ON for at most 1s
          - OFF for at least 0.1s
        then:
          - if:
              condition:
                api.connected:
              then:
                # send double click event
                - homeassistant.event:
                    event: esphome.${device_name}
                    data:
                      title: button 1 double click            
              else:
                # publish mqtt double click
                - mqtt.publish:
                    topic: ${device_name}/button/1/command
                    payload: "DOUBLE_CLICK"
      # button held
      - timing:
          - ON for at least 0.75s
        then:
          - delay: 0.25s
          - while:
              condition:
                - binary_sensor.is_on: button1
              then:
                - if:
                    condition:
                      api.connected:
                    then:
                      # send hold event
                      - homeassistant.event:
                          event: esphome.${device_name}
                          data:
                            title: button 1 hold            
                    else:
                      # publish mqtt hold
                      - mqtt.publish:
                          topic: ${device_name}/button/1/command
                          payload: "HOLD"
                      - delay: 0.1s
      # single click
      - timing:
          - ON for at most 0.75s
          - OFF for at least 0.5s
        then:
          - if:
              condition:
                api.connected:
              then:
                # send short click event
                - homeassistant.event:
                    event: esphome.${device_name}
                    data:
                      title: button 1 short click            
              else:
                # publish mqtt double click
                - mqtt.publish:
                    topic: ${device_name}/button/1/command
                    payload: "SHORT_CLICK"       
    # on_release:
    #   - homeassistant.event:
    #       event: esphome.${device_name}
    #       data:
    #         title: button 1 released
    internal: true
    id: button1
    filters:
      - delayed_on_off: 50ms