# Device Specific Config
esphome:
  name: ${name}
  comment: ${device_description}
  project:
    name: "${project_name}"
    version: "${project_version}"

esp32:
  board: esp32dev
  framework: 
    type: arduino
# external_components:
#   # - source: github://pr#4330
#   #   components: [internal_temperature]
#   #   refresh: always
#   # - source: my_external_components/test/ng_v0.1
#   #   refresh: always
#   - source: github://ashp8i/esphome-components
#     refresh: always

captive_portal:

web_server:

i2c:
