mqtt:
  broker: !secret mqtt_ip
  username: !secret mqtt_username
  password: !secret mqtt_password
  # discovery: true
  on_message:
    # Switch 1 - Button 1
    - topic: $switch1b1_topic
      payload: 'SHORT_CLICK'
      qos: 0
      then:
        - light.toggle: ${main_device_id}
    - topic: $switch1b1_topic
      payload: 'HOLD'
      qos: 0
      then:
        # Increase the brightness by 5%
        - light.dim_relative:
            id: ${main_device_id}
            relative_brightness: 5%
            transition_length: 0.1s
        - delay: 0.1s
    - topic: $switch1b1_topic
      payload: 'DOUBLE_CLICK'
      qos: 0
      then:
        - lambda: |-
            float current_temp = id(${main_device_id}).current_values.get_color_temperature();
            auto call = id(${main_device_id}).turn_on();
            call.set_color_temperature(current_temp + 25);
            call.set_transition_length(1000); // in ms
            call.perform();
    # Switch 2 - Button 1
    - topic: $switch2b1_topic
      payload: 'SHORT_CLICK'
      qos: 0
      then:
        - light.toggle: ${main_device_id}
    - topic: $switch2b1_topic
      payload: 'HOLD'
      qos: 0
      then:
        # Increase the brightness by 5%
        - light.dim_relative:
            id: ${main_device_id}
            relative_brightness: 5%
            transition_length: 0.1s
        - delay: 0.1s
    - topic: $switch2b1_topic
      payload: 'DOUBLE_CLICK'
      qos: 0
      then:
        - lambda: |-
            float current_temp = id(${main_device_id}).current_values.get_color_temperature();
            auto call = id(${main_device_id}).turn_on();
            call.set_color_temperature(current_temp + 25);
            call.set_transition_length(1000); // in ms
            call.perform();
    # Switch 2 - Button 2
    - topic: $switch2b2_topic
      payload: 'SHORT_CLICK'
      qos: 0
      then:
        - light.toggle: ${main_device_id}
    - topic: $switch2b2_topic
      payload: 'HOLD'
      qos: 0
      then:
        # Decreases the brightness by 5%
        - light.dim_relative:
            id: ${main_device_id}
            relative_brightness: -5%
            transition_length: 0.1s
        - delay: 0.1s
    - topic: $switch2b2_topic
      payload: 'DOUBLE_CLICK'
      qos: 0
      then:
        - lambda: |-
            float current_temp = id(${main_device_id}).current_values.get_color_temperature();
            auto call = id(${main_device_id}).turn_on();
            call.set_color_temperature(current_temp - 25);
            call.set_transition_length(1000); // in ms
            call.perform();
    # Switch 3 - Button 1
    - topic: $switch3b1_topic
      payload: 'SHORT_CLICK'
      qos: 0
      then:
        - light.toggle: ${main_device_id}
    - topic: $switch3b1_topic
      payload: 'HOLD'
      qos: 0
      then:
        # Increases the brightness by 5%
        - light.dim_relative:
            id: ${main_device_id}
            relative_brightness: 5%
            transition_length: 0.1s
        - delay: 0.1s
    - topic: $switch3b1_topic
      payload: 'DOUBLE_CLICK'
      qos: 0
      then:
        - lambda: |-
            float current_temp = id(${main_device_id}).current_values.get_color_temperature();
            auto call = id(${main_device_id}).turn_on();
            call.set_color_temperature(current_temp - 25);
            call.set_transition_length(1000); // in ms
            call.perform();
    # Switch 3 - Button 2
    - topic: $switch3b2_topic
      payload: 'SHORT_CLICK'
      qos: 0
      then:
        - light.toggle: ${main_device_id}
    - topic: $switch3b2_topic
      payload: 'HOLD'
      qos: 0
      then:
        # Decreases the brightness by 5%
        - light.dim_relative:
            id: ${main_device_id}
            relative_brightness: -5%
            transition_length: 0.1s
        - delay: 0.1s
    - topic: $switch3b2_topic
      payload: 'DOUBLE_CLICK'
      qos: 0
      then:
        - lambda: |-
            float current_temp = id(${main_device_id}).current_values.get_color_temperature();
            auto call = id(${main_device_id}).turn_on();
            call.set_color_temperature(current_temp + 25);
            call.set_transition_length(1000); // in ms
            call.perform();
