# Device Specific Config
  esphome:
    name: ${device_name}
    comment: ${device_description}
    platformio_options:
      platform_packages:
      # - framework-arduinoespressif32 @ https://github.com/tasmota/arduino-esp32.git#Tasmota/205
      # - framework-arduinoespressif32 @ https://github.com/tasmota/arduino-esp32/releases/download/2.0.5.1/framework-arduinoespressif32-solo1.zip
      - framework-arduinoespressif32 @ https://github.com/tasmota/arduino-esp32/releases/download/2.0.5/framework-arduinoespressif32-solo1.zip
      board_build.f_cpu: 160000000L
    project:
      name: "${project_name}"
      version: "${project_version}"
  
  esp32:
    board: esp32doit-devkit-v1
    # board: esp32-solo1
    variant: esp32
    framework:
      type: arduino
      platform_version: 5.2.0
      # sdkconfig_options:
      #   CONFIG_FREERTOS_UNICORE: y
      #   CONFIG_ESP32_DEFAULT_CPU_FREQ_160: y
      #   CONFIG_ESP32_DEFAULT_CPU_FREQ_MHZ: "160"

  captive_portal:

  web_server:
    port: 80
    auth:
      username: admin
      password: !secret web_server_password
    include_internal: true
    local: true