# Device Specific Config
  esphome:
    name: ${name}
    comment: ${device_description}
    platformio_options:
      board_build.f_cpu: 160000000L
    project:
      name: "${project_name}"
      version: "${project_version}"
  
  esp32:
    board: esp32doit-devkit-v1
    framework:
      type: esp-idf
      sdkconfig_options:
        CONFIG_FREERTOS_UNICORE: y
        CONFIG_ESP32_DEFAULT_CPU_FREQ_160: y
        CONFIG_ESP32_DEFAULT_CPU_FREQ_MHZ: "160"