binary_sensor:
  - platform: status
    name: "${friendly_name} Status"
  - platform: gpio
    pin:
      number: GPIO17
      mode: INPUT_PULLDOWN
    name: ${sensor_name}
    device_class: ${sensor_class}
    filters:
      - invert:
    on_state:
      then:
        - switch.toggle: relay_1
        - http_request.post: http://store.local/light/store/toggle
        # - mqtt.publish:
        #     topic: ${name}/button/2/command
        #     payload: "SHORT_CLICK"
