# Device Specific Config
esphome:
  name: ${device_name}
# name_add_mac_suffix: true
  comment: ${device_description}
  platformio_options:
    board_build.f_cpu: 160000000L
  project:
    name: "${project_name}"
    version: "${project_version}"

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y
      CONFIG_ESP32_DEFAULT_CPU_FREQ_160: y
      CONFIG_ESP32_DEFAULT_CPU_FREQ_MHZ: "160"

external_components:
  - source: github://pr#4330
    components: [internal_temperature]
    refresh: always
  - source: github://pr#3500
  # - source: github://dentra/esphome@web-server-idf
    components:
      - web_server
      - web_server_idf
      - web_server_base
      - captive_portal
    refresh: 100days
  - source:
      type: local
      path: .external_components

#  captive_portal:

web_server:
#    port: 80
#    auth:
#      username: admin
#      password: !secret web_server_password
#    include_internal: true
#    local: true

time:
  - platform: homeassistant
    id: homeassistant_time

# i2c sensor
i2c:
  sda: GPIO16
  scl: GPIO19
  scan: false
  id: bus_a

shelly_dallas:
  pin_a: GPIO3
  pin_b: GPIO0

# # Device Specific Config
# i2c:
#   sda: GPIO12
#   scl: GPIO14

output:
  - platform: gpio
    id: "relay_output"
    pin: GPIO26

# Commented out to avoid duplicates keys in config see .base.switch-shelly-2.5-generic.yaml
# switch:
#   - platform: output
#     name: "${device_name} Switch 1"
#     output: shelly_25_relay_1
#     id: switchid1

# status_led:
#   pin:
#     number: GPIO0
#     inverted: true

