esphome:
  name: "${device_name}"
  # name_add_mac_suffix: true
  comment: ${device_description}
  platform: ESP8266
  board: esp01_1m
  project:
    name: "${project_name}"
    version: "${project_version}"

captive_portal:

web_server:
  port: 80
  auth:
    username: admin
    password: !secret web_server_password
  include_internal: true
  # local: true

# globals:
#   - id: last_light_on
#     type: int
#     restore_value: no
#     initial_value: '1'

# Device Specific Config
output:
  - platform: gpio
    pin: GPIO4
    id: shelly_1_relay

# Commented out to avoid duplicates keys in config see .base.switch-shelly-1-generic.yaml
# switch:
#   - platform: output
#     name: "Shelly 1 Switch"
#     output: shelly_1_relay
#     id: ${main_device_id}