esphome:
  name: "${name}"
  # name_add_mac_suffix: true
  comment: ${device_description}
  platformio_options:
    platform_packages:
    # - framework-arduinoespressif32 @ https://github.com/tasmota/arduino-esp32/releases/download/2.0.7/framework-arduinoespressif32-solo1.zip
    - framework-arduinoespressif32 @ https://github.com/tasmota/arduino-esp32/releases/download/2.0.5/framework-arduinoespressif32-solo1.zip
    board_build.f_cpu: 160000000L
  project:
    name: "${project_name}"
    version: "${project_version}"

esp32:
  board: esp32doit-devkit-v1
  variant: esp32
  framework:
    type: arduino
    # platform_version: 5.2.0
    platform_version: 6.1.0

# external_components:
#   - source:
#       type: local
#       path: my_external_components/test5

captive_portal:

web_server:
  port: 80
  auth:
    username: admin
    password: !secret web_server_password
  include_internal: true
  # local: true

time:
  - platform: homeassistant
    id: homeassistant_time  

# Device Specific Config
i2c:
  sda: GPIO12
  scl: GPIO14

output:
  - platform: gpio
    id: "relay_output"
    pin: GPIO26

light:
  - platform: binary
    name: "${friendly_name}"
    output: relay_output
    id: ${device_id_white}
    icon: ${light_icon}

# onewirebus:
#  input_pin: GPIO1
#  output_pin: GPIO0

# Commented out to avoid duplicates keys in config see .base.switch-shelly-2.5-generic.yaml
# switch:
#   - platform: output
#     name: "${name} Switch 1"
#     output: shelly_25_relay_1
#     id: switchid1
#   - platform: output
#     name: "${name} Switch 2"
#     output: shelly_25_relay_2
#     id: switchid2