binary_sensor:
  - platform: status
    name: "${friendly_name} Status"
  - platform: gpio
    name: "${friendly_name} Button 1"
    pin:
      number: GPIO12
      mode:
        input: true
    on_multi_click:
      # double click
      - timing:
          - ON for at most 1s
          - OFF for at most 1s
          - ON for at most 1s
          - OFF for at least 0.1s
        then:
          # send double click event
          - homeassistant.event:
              event: esphome.${name}
              data:
                title: button 1 double click
        # button held
      - timing:
          - ON for at least 0.75s
        then:
          - delay: 0.25s
          - while:
              condition:
                - binary_sensor.is_on: button1
              then:
                # send hold event
                - homeassistant.event:
                    event: esphome.${name}
                    data:
                      title: button 1 hold
                - delay: 0.1s
        # single click
      - timing:
          - ON for at most 0.75s
          - OFF for at least 0.5s
        then:
          # send short click event
          - homeassistant.event:
              event: esphome.${name}
              data:
                title: button 1 short click
    # on_release:
    #   - homeassistant.event:
    #       event: esphome.${name}
    #       data:
    #         title: button 1 released
    internal: true
    id: button1
    filters:
      - delayed_on_off: 50ms