# Device Specific Config
esphome:
  name: ${device_name}
  comment: ${device_description}
  platform: ESP32
  board: esp32dev

captive_portal:

web_server:
  port: 80
  auth:
    username: admin
    password: !secret web_server_password
  include_internal: true
  # local: true

output:
  - platform: ledc
    id: output_red
    pin: GPIO5
    # max_power: 100%
    frequency: ${frequency_rgb}
  - platform: ledc
    id: output_green
    pin: GPIO14
    # max_power: 100%
    frequency: ${frequency_rgb}
  - platform: ledc
    id: output_blue
    pin: GPIO16
    # max_power: 100%
    frequency: ${frequency_rgb}
  - platform: ledc
    id: output_cold_white
    max_power: 100%
    frequency: ${frequency_cw}
    pin: GPIO17
  - platform: ledc
    id: output_warm_white
    pin: GPIO18
    max_power: 100%
    frequency: ${frequency_ww}

remote_receiver:
  pin:
    number: GPIO27
    inverted: True
  dump: nec
#  tolerance: 20%
#  buffer_size: 1kB
#  filter: 2us
#  idle: 4ms

wled:

e131:
  method: multicast # default: register E1.31 to Multicast group

light:
  - platform: cwww
    name: ${friendly_name}
    id: ${main_device_id}
    cold_white: output_cold_white
    warm_white: output_warm_white
    cold_white_color_temperature: 6536 K
    warm_white_color_temperature: 2000 K
    constant_brightness: false
    gamma_correct: 0
    default_transition_length: 1s
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
    - globals.set:
        id: last_light_on
        value: '1'
    icon: "hue:ceiling-aurelle-circle"
  - platform: rgb
    name: ${friendly_name_rgb}
    id: ${device_name_rgb}
    red: output_red
    green: output_green
    blue: output_blue
    default_transition_length: 0.5s
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
    - globals.set:
        id: last_light_on
        value: '2'
    icon: "hue:ceiling-muscari"
    <<: !include .base.light-rgb-effects.yaml