mqtt:
  broker: !secret mqtt_ip
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true
  on_message:
    - topic: $switch1_topic
      payload: 'SHORT_CLICK'
      qos: 0
      then:
        - light.toggle: ${main_device_id}
    - topic: $ikea_tradfri_topic
      payload: 'toggle'
      qos: 0
      then:
        - light.toggle: ${main_device_id}