# Device Specific Config
esphome:
  name: ${name}
  comment: ${device_description}
  project:
    name: "${project_name}"
    version: "${project_version}"

esp32:
  board: esp32dev
  framework: 
    type: arduino

external_components:
  # - source: github://pr#4330
  #   components: [internal_temperature]
  #   refresh: always
  # - source: my_external_components/test/ng_v0.1
  #   refresh: always
  - source: github://ashp8i/esphome-components
    refresh: always

captive_portal:

web_server:

# onewire_bus:
#   pin: GPIO5
#   mode: normal
# ds28e17_i2c_bus:
# custom_onewire:
#   pin: GPIO5
# esponewire:
#   pin: GPIO5
# owng_bus:
#   # id: my_onewire_component
#   pin: 'GPIO18'
#   split_io: false
ow_bus_ng_single_pin_hybrid:
  pin: GPIO18
  mode: 'single_pin_hybrid'
# ow_bus_ng:
#   input_pin: 'GPIO19'
#   output_pin: 'GPIO20'
#   mode: 'bitbang_split_io'
