esphome:
  name: ${device_name}
  comment: ${device_description}
  platformio_options:
    board_build.flash_mode: dio
  project:
    name: "${project_name}"
    version: "${project_version}"

esp32:
  # board: um_tinys2
  board: esp32-s2-saola-1
  framework:
    type: esp-idf

output:
  - platform: ledc
    id: output_cold_white
    pin: GPIO4
  - platform: ledc
    id: output_warm_white
    pin: GPIO5

light:
  - platform: cwww
    name: ${friendly_name}
    id: ${main_device_id}
    cold_white: output_cold_white
    warm_white: output_warm_white
    cold_white_color_temperature: 6536 K
    warm_white_color_temperature: 2000 K
    constant_brightness: false
    gamma_correct: 0
    default_transition_length: 1s
    icon: "hue:ceiling-aurelle-circle"