# Device Specific Config
esphome:
  name: ${device_name}
  comment: ${device_description}
  project:
    name: "${project_name}"
    version: "${project_version}"

esp32:
  board: esp32dev
  framework: 
    type: arduino

external_components:
  # - source: github://pr#4330
  #   components: [internal_temperature]
  #   refresh: always
  # - source: my_external_components/test/ng_v0.1
  #   refresh: always
  - source: github://ashp8i/esphome-components
    refresh: always


captive_portal:

web_server:

uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600
  # half_duplex: true

# onewire_bus:
#   pin: GPIO5
#   mode: normal
# ds28e17_i2c_bus:
# custom_onewire:
#   pin: GPIO5
# esponewire:
#   pin: GPIO5
# owng_bus:
#   # id: my_onewire_component
#   pin: 'GPIO18'
#   split_io: false
# ow_bus_ng:
  # - id: test
    # pin: 21
    # pin: GPIO12
  # pin_option: 'single'
  # input_pin: 'GPIO19'
  # output_pin: 'GPIO20'
    # mode: 'bitbang_single'
# ow_bus_ng:
#   pin_option: 'split_io'
    # input_pin: 'GPIO19'
    # output_pin: 'GPIO20'
    # mode: 'bitbang_split_io'