# Enable logging
# Logger must be at least debug (default)
logger:
  level: VERBOSE
  baud_rate: 0
  logs:
    onewirebus.component: VERBOSE

ota:
  safe_mode: true
  password: !secret ota_password

wifi:
    ssid: !secret wifi_all_ssid
    password: !secret wifi_all_password

    # Enable fallback hotspot (captive portal) in case wifi connection fails
    ap:
      ssid: ${device_ssid} Fallback Hotspot
      password: !secret ap_password