# Device Specific Config
esphome:
  name: "${device_name}"
  # name_add_mac_suffix: true
  comment: ${device_description}
  platform: ESP8266
  board: esp_wroom_02
  project:
    name: "${project_name}"
    version: "${project_version}"

external_components:
  - source:
      type: local
      path: .external_components/tuya_cover_custom

captive_portal:

web_server:
  port: 80
  auth:
    username: admin
    password: !secret web_server_password
  include_internal: true
  local: true


uart:
    rx_pin: GPIO13
    tx_pin: GPIO15
    baud_rate: 9600
    debug:
      direction: BOTH
      dummy_receiver: false
      sequence:
        - lambda: UARTDebug::log_hex(direction, bytes, ':');

# Register the Tuya MCU connection
# tuya:
tuya_custom:

cover:
  - platform: "tuya_custom"
    id: "${main_device_id}"
    name: "${cover_name}"
    control_datapoint: 102
    position_datapoint: 101
    position_report_datapoint: 101
    # direction_datapoint incorrect helps for now as the reporting is inverted but commands register correctly.
    # invert position fixes the inverted reporting as long as the datapoint is set incorrectly.
    direction_datapoint: 99
    # direction_datapoint: 103 (old reference)
    min_value: 0
    max_value: 100
    invert_position: true
    device_class: curtain

