mqtt:
  broker: !secret mqtt_ip
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true
  on_message:
    - topic: $lonsonho_dual_topic
      payload: '2_single'
      qos: 0
      then:
        - fan.toggle: ${device_id_white}_fan