esphome:
  name: "${device_name}"
  # name_add_mac_suffix: true
  comment: ${device_description}
  platformio_options:
    platform_packages:
    # - framework-arduinoespressif32 @ https://github.com/tasmota/arduino-esp32/releases/download/2.0.7/framework-arduinoespressif32-solo1.zip
    - framework-arduinoespressif32 @ https://github.com/tasmota/arduino-esp32/releases/download/2.0.5/framework-arduinoespressif32-solo1.zip
    board_build.f_cpu: 160000000L
  project:
    name: "${project_name}"
    version: "${project_version}"

esp32:
  board: esp32doit-devkit-v1
  variant: esp32
  framework:
    type: arduino
    platform_version: 5.2.0

external_components:
  - source:
      type: local
      path: my_external_components/test4

captive_portal:

web_server:
  port: 80
  auth:
    username: admin
    password: !secret web_server_password
  include_internal: true
  # local: true

time:
  - platform: homeassistant
    id: homeassistant_time  

# Device Specific Config
i2c:
  sda: GPIO26
  scl: GPIO25

output:
  - platform: gpio
    id: "relay_output_1"
    pin: GPIO13

  - platform: gpio
    id: "relay_output_2"
    pin: GPIO12



# onewirebus:
#   input_pin: GPIO1
#   output_pin: GPIO0

# Commented out to avoid duplicates keys in config see .base.switch-shelly-2.5-generic.yaml
# switch:
#   - platform: output
#     name: "${device_name} Switch 1"
#     output: shelly_25_relay_1
#     id: switchid1
#   - platform: output
#     name: "${device_name} Switch 2"
#     output: shelly_25_relay_2
#     id: switchid2