binary_sensor:
  - platform: status
    name: "${friendly_name} Status"
  - platform: gpio
    name: "${friendly_name} Button 1"
    pin:
      number: GPIO12
      mode:
        input: true
    on_multi_click:
      # double click
      - timing:
          - ON for at most 0.35s
          - OFF for at most 0.35s
          - ON for at most 0.35s
          - OFF for at least 0.1s
        then:
          # publish mqtt double click
          - mqtt.publish:
              topic: ${device_name}/button/1/command
              payload: "DOUBLE_CLICK"
        # button held
      - timing:
          - ON for at least 0.5s
        then:
          - delay: 0.05s
          - while:
              condition:
                - binary_sensor.is_on: button1
              then:
                # publish mqtt hold
                - mqtt.publish:
                    topic: ${device_name}/button/1/command
                    payload: "HOLD"
                  - delay: 0.05s
                - delay: 0.05s
        # single click
      - timing:
          - ON for at most 0.9s
          - OFF for at least 0.1s
        then:
          # publish mqtt short click
          - mqtt.publish:
              topic: ${device_name}/button/1/command
              payload: "SHORT_CLICK"
    # on_release:
    #   - homeassistant.event:
    #       event: esphome.${device_name}
    #       data:
    #         title: button 1 released
    internal: true
    id: button1
    filters:
      - delayed_on_off: 50ms
  - platform: gpio
    name: "${friendly_name} Button 2"
    pin:
      number: GPIO14
      mode:
        input: true
    on_multi_click:
      # double click
      - timing:
        - ON for at most 0.35s
        - OFF for at most 0.35s
        - ON for at most 0.35s
        - OFF for at least 0.1s
        then:
          # publish mqtt double click
          - mqtt.publish:
              topic: ${device_name}/button/2/command
              payload: "DOUBLE_CLICK"
        # button held
      - timing:
          - ON for at least 0.5s
        then:
          - delay: 0.05s
          - while:
              condition:
                - binary_sensor.is_on: button2
              then:
                # publish mqtt hold
                - mqtt.publish:
                    topic: ${device_name}/button/2/command
                    payload: "HOLD"
                      - delay: 0.05s
                - delay: 0.05s
        # single click
      - timing:
          - ON for at most 0.9s
          - OFF for at least 0.1s
        then:
          # publish mqtt short click
          - mqtt.publish:
              topic: ${device_name}/button/2/command
              payload: "SHORT_CLICK"
    # on_release:
    #   - homeassistant.event:
    #       event: esphome.${device_name}
    #       data:
    #         title: button 2 released
    internal: true
    id: button2
    filters:
      - delayed_on_off: 50ms