substitutions:
  device_ssid: "Extra 30W"
  device_name: extra30w
  device_description: "ZH United 30W CCT Slim Ceiling Light"
  friendly_name: "Extra 30W"    # Put the name that you want to see in Home Assistant.
  device_id_white: "extra30w"    # Put the name that you want to see in Home Assistant.
  tradfri_topic: ashishswitch-/button/1/command
  project_name: "zhunited.30w-cw-slim-ceiling-light-esp32-c3-arduino-cct"
  project_version: "1.0"

# Enable Home Assistant API
api:
  encryption:
    key: !secret extra30w_noise_key
  reboot_timeout: 0s

<<: !include .base-debug.yaml
<<: !include .base.device.light.zhunited-40w-jl-02-ceiling-light-esp32-c3-arduino-cct.yaml
<<: !include .base.global-mqtt-automation-cct.yaml
# <<: !include .base.automation.light-mqtt-1-button-plus-2-button-switch.yaml
<<: !include .base.common-sensor-die-temp.yaml
<<: !include .base.common-button.yaml
<<: !include .base.common-text-sensor.yaml
<<: !include .base.common-binary-sensor.yaml