---
# WiFi - Unified
wifi_all_ssid: "Matrix"
wifi_all_password: "g7n9-3be7-o5xs"

# AP
ap_password: "IZBguOU56n3l"

# Over The Air
ota_password: "P0!s0n@rr0w2019!"

# API
api_password: "P0!s0n@rr0w2019!"

# Your Wi-Fi SSID and password
wifi_ssid: "Matrix"
wifi_password: "g7n9-3be70o5xs"

# Web Server Password
web_server_password: "P0!s0n@rr0w2019!"

# MQTT
mqtt_ip: 10.10.1.7
mqtt_username: mosquitto
mqtt_password: XiZnFL7F

# Noise Encryption Keys
bedroom2_noise_key: "KWTQC3odc2IdpGVety/CfnzbjoZYc/x00S6/FBAOaHQ="
bathentrancerelay_noise_key: "OqCUGoNULAPZkU47FuU57JPuitMlW7qafMDq2xgucWg="
bathroomrelay_noise_key: "99CT7vsdBs6nRVPUplfq0qjygTHtiAMU9wjoVsgOOsI="
bathroomwallrelay_noise_key: "t7xuzT97rmOSjnnDJc6XDkDsOoQ4TXdlPHQMJ7/p5XA="
toiletrelay_noise_key: "ovGb3hZ0VDftpUvFsMDWc/zxPZqcd+XlGfYnaom6ETM="
stairs_noise_key: "g2y5Ipu+YNXDJrP1srHL7Soe6wX2l+Uw3XqJPgEUBAk="
bedroom2bulb1_noise_key: "I3BQg9BiIc7Nwlgd5GnP4kq13m8dRg76BHQ+DTPgG68="
bedroom2bulb2_noise_key: "8LFswlWpcTwIcgG8EaSa7Oe/w3OR1QOzGy2PzUrX32A="
bedroom2bulb3_noise_key: "cbFCNflcGBVaSAV7VL2l2IP4MILjoAa2VdAZ0EDnFfQ="
bedroom2bulb4_noise_key: "FVJMo4xmendRlsYmCk4tNTYcQ7UA+Y0L321JGsqDNaI="
bedroom2bulb5_noise_key: "LW0X8UDCaazyGcJe7teNqmPsKmrY6mP8A19JVXGSUtk="
bedroom2bulb6_noise_key: "kkmIwxx3fWw1ymxOYu03GUuBT2y9StxGnRuv9dBCMJA="
bedroom2switch1_noise_key: "6Y23Z6IRAMWdB8EjlBQjv6ctNGVEtcDKKrFv/sDg9Aw="
bedroom2switch2_noise_key: "qi0kHErRkSZlHHwgFYGpQOGv7TNy2FvJdxG5mOQvd5M="
masterbedroom1_noise_key: "ZimOqdZ5Bn1r+LlKiUcxDjJg+SlroEqTg4nwtzyJG7s="
masterbedroom2_noise_key: "I1xJlCCqZn1SxvvtRFyBg2VfZ5hb3090aaBFXXDtEzQ="
masterswitch_noise_key: "SpNDS/98+q1nBjZZi5IpoIwztJYcnTFY3C9BZ5FW+OI="
lowerloftstairs_noise_key: "Qk8XDM9U6zlIZTeDv9zROuyyUUP3AQzllybwF1pLfNE="
upperloftstairs_noise_key: "PD32J/TX+OpbFTBgtFrTRQHMkkDgslWHWtgItjwhRDA="
front_entrance_noise_key: "eavQYMa3Bu7MLXlGUHm7tYFwcyWCoMQsBUyk5Pl42Co="
front_porch_noise_key: "Xv5mvBire8JTELbTwqNk7ZgeKrQUc1MzBwGJwRb/J10="
front_passage1_noise_key: "oifxgo1bWgin39x7POP489O9wgYK+f4xGzgCvX+O1TM="
front_passage2_noise_key: "RTD9C3mp6qWgP986ezp6Ta9krRI8Hdc47q0Aje2boI4="
front_passage3_noise_key: "1sqAKDr7mzut00HoPZn0JHOHMH82hm4nRR8Epumq2YQ="
living_noise_key: "sG50MZMFN1RK0iqPJn/mCPUSTiqCSF8AE/pi0PEFnN4="
dining_noise_key: "RRz0F3VkksmsdJWb2PmPQVvrsqPB5qt6abzMCS3R+JY="
loftswitch_noise_key: "28aE8hBxu6Tr4ybdCwkXdzQfLMkX83KN9cZQZ/EoNhE="
frontswitch_noise_key: "gZpxYARdRs/d4QWxUd88MIs0zKPlxS9iRiJvQvcgB6Y="
stairsswitch1_noise_key: "THX08vVhlHSdcXwVT+w3h9EvQlh5E6DmSD3w/NUVBf4="
stairsswitch2_noise_key: "raz3+cJ7CYUzSW9W4Dc0ZXiDvkWiJDtHSEgtb19Iglg="
passageswitch1_noise_key: "g99bqhfy9axMv94crF4w10weow7XORAd0nFL1bCuTpM="
passageswitch2_noise_key: "uEAhLrOQY1BAJu/9PEc9++uoRdUGEOK6sgv43QrIoek="
livingswitch_noise_key: "0wA2xybTIMDeoHjtglY9Jwz5PzvXZD06nJaA3bMmEcU="
diningswitch_noise_key: "+9eyYxXg3Y5KFTU4kZ6eknHD8YwoVPY24QTjqomf3mM="
livingcurtain_noise_key: "PXbahs3SWBnlUO+MJn1EAqDXkidHYkRepQbdw11SQKg="
diningcurtain_noise_key: "hZK0IKDfsh/VvQFDfVNlOALDip+HbFxAwzFotz/9Ka4="
bedroom3_noise_key: "Th0WkTBPUK5WtF6DGJWBKgbDHzi8KdQ+niWdq1yhS1s="
bathroom_noise_key: "FdDryje6mPSCmYus7qV/6sfWseu5LwtvmkmS16xGC98="
frontentrancemotion_noise_key: "ZCs2j8I1bQsB6XXkt/IfVvAsAmWP96xrRbYJjTDp+Fg="
passagemotion_noise_key: "FCOS5oeTHBaiu2OmnJAO/k1OmJaQbxioto36KOmWJMw="
stairsmotion_noise_key: "scYmstWXh+t+062GkXYDAYGAj+At9ETioIManxducn0="
bedroom3switch_noise_key: "vDKDAWcjdn+NDuivBeOcoq8r+44jxWr7zLzoeSFAD54="
spare_rashila_noise_key: "E2bFqDGvSAK8ZCYOj4Cstj6EkH3zcHepoJcqbY405F0="
spare_bathroom_noise_key: "sH35dcyYAmAy4IHeSeqClldtcfLXofKo5FvLWkUGlrA="
extra30w_noise_key: "z0bdT6Jl7TdGrRK70q8Hpx5XDTU6wERpCBBZLuNBUBI="
bedroom2lamp2_noise_key: "P1zpAcSQ4n8Wkt0EiNBHuNl1KlU7cswgqgt+uawQHb8="
# Example Noise Key
new_noise_key: "IZssHkUmXlcc/FHsvZRagKFmtXHLuqjjUuTmdMV5eDQ="
new_noise_key2: "LRsmzEanuiXlpl1ojEeg4M8q3FGS7a2IcYsPe3FQqjY="

# http authentication string
http_auth: YWRtaW46UDAhczBuQHJyMHcyMDE5IQ==