substitutions:
  name: "bedroom2spot6"
  device_ssid: "Bed 2 Spot 6"
  device_main_id: bedroom2spotsixcct
  device_description: "Athom GU10 RGBCW LB10-5W-ESP-1"
  friendly_name: "Bedroom 2 Spot 6"    # Put the name that you want to see in Home Assistant.
  device_name_rgb: bedroom2spot6rgb
  device_description_rgb: "Bedroom 2 Spot 6 RGB."    # Put the name that you want to see in Home Assistant.
  friendly_name_rgb: "Bedroom 2 Spot 6 RGB"    # Put the name that you want to see in Home Assistant.
  main_device_id: "bedroom2spot6"    # Put the name that you want to see in Home Assistant.
  switch1b1_topic: bedroom2switch2/button/1/command
  switch1b2_topic: bedroom2switch2/button/2/command
  switch1b3_topic: bedroom2switch2/button/3/command
  switch1b4_topic: bedroom2switch2/button/4/command
  light_icon: "hue:bulb-spot-hung"
  light_icon_2: "hue:bulb-spot-hung"
  project_name: "athom.rgbww-light"
  project_version: "1.0"
  # frequency_rgb: 250 Hz
  frequency_cw: 1000 Hz
  frequency_ww: 1000 Hz
  
# Enable Home Assistant API
api:
  encryption:
    key: !secret bedroom2bulb6_noise_key
  reboot_timeout: 0s

<<: !include .base-debug.yaml
<<: !include .base.device.bulb.athom-gu10.yaml
<<: !include .base.automation.light-mqtt-4-button-rgbcct.yaml
<<: !include .base.common-binary-sensor.yaml
<<: !include .base.common-sensor.yaml
<<: !include .base.common-switch.yaml
<<: !include .base.common-text-sensor.yaml
      