substitutions:
  name: "bedroom2wardrobeblind"
  device_ssid: "Bedroom 2 WB"
  device_description: "Zemismart M515EGWT Blind Motor ESP32-C3"
  friendly_name: "Bedroom 2 Wardrobe Blind" # Put the name that you want to see in Home Assistant.
  device_id: "bedroom2cover" # Put the name that you want to see in Home Assistant.
  cover_name: "Bedroom 2 Wardrobe Blind"
  project_name: "zemismart.m515egwt-esp32-c3-arduino"
  project_version: "1.0"

# Enable Home Assistant API
api:
  encryption:
    key: !secret bedroom2wardrobeblind_noise_key
  reboot_timeout: 0s

<<: !include .base-debug-tuya-verbose.yaml
<<: !include .base.device.curtain.zemismart-m515egwt-esp32-c3-arduino.yaml
<<: !include .base.common-binary-sensor.yaml
<<: !include .base.common-sensor.yaml
<<: !include .base.button-zemismart-m515egwt.yaml
<<: !include .base.common-text-sensor.yaml