substitutions:
  device_ssid: "Dining Curtain"
  device_name: diningcurtain
  device_description: "Zemismart BCM500DS-TYW Curtain Motor"
  friendly_name: "Dining Curtain" # Put the name that you want to see in Home Assistant.
  main_device_id: "diningcurtain" # Put the name that you want to see in Home Assistant.
  cover_name: "Dining Curtain"
  project_name: "zemismart.bcm500ds-tyw"
  project_version: "1.0"

# Enable Home Assistant API
api:
  encryption:
    key: !secret diningcurtain_noise_key
  reboot_timeout: 0s

<<: !include .base-debug-tuya-verbose.yaml
<<: !include .base.device.curtain.zemismart-bcm500ds-tyw-working.yaml
<<: !include .base.common-binary-sensor.yaml
<<: !include .base.common-sensor.yaml
<<: !include .base.common-switch.yaml
<<: !include .base.common-text-sensor.yaml