substitutions:
  name: livingcurtain
  device_ssid: "Living Curtain"
  device_description: "Zemismart BCM500DS-TYW Curtain Motor"
  friendly_name: "Living Curtain" # Put the name that you want to see in Home Assistant.
  device_id_white: "livingcurtain" # Put the name that you want to see in Home Assistant.
  cover_name: "Living Curtain"
  project_name: "zemismart.bcm500ds-tyw"
  project_version: "1.0"

# Enable Home Assistant API
api:
  encryption:
    key: !secret livingcurtain_noise_key
  reboot_timeout: 0s

<<: !include .base-debug-tuya.yaml
<<: !include .base.device.curtain.zemismart-bcm500ds-tyw-esp32-s3.yaml
<<: !include .base.common-binary-sensor.yaml
<<: !include .base.common-sensor.yaml
<<: !include .base.common-button.yaml
<<: !include .base.common-text-sensor.yaml