substitutions:
  name: livingspots
  device_ssid: "Living Spots"
  device_description: "MiBoxer TRI-C1WR Tuya ESP32-C3 LED Dimmer."
  friendly_name: "Living Spots" # Put the name that you want to see in Home Assistant.
  device_id_white: "livingspots" # Put the name that you want to see in Home Assistant.
  light_icon: "hue:bulb-group-spot-hung"
  api_key: !secret livingspots_noise_key
  project_name: "miboxer.tri-c1wr-esp32-c3-arduino"
  project_version: "1.0"

packages:
  - !include packages/base/debug.yaml
  - !include packages/common/api.yaml
  - !include packages/devices/light.miboxer-tri-c1wr-esp32-c3.yaml
  - !include packages/common/api.yaml
  - !include packages/common/mqtt.yaml
  - !include packages/common/sensor-die-temp.yaml
  - !include packages/common/button.yaml
  - !include packages/common/text-sensor.yaml
  - !include packages/switch/miboxer-tri-c1wr.yaml