substitutions:
  name: masterbedroom2
  device_ssid: "Master 2"
  device_description: "MiBoxer FUT035W Tuya ESP32-C3 LED Controller."
  friendly_name: "Master Bedroom 2" # Put the name that you want to see in Home Assistant.
  device_id_white: "masterbedroom2" # Put the name that you want to see in Home Assistant.
  switch1b1_topic: masterswitch/button/1/command
  light_icon: "hue:lightstrip"
  project_name: "miboxer.fut035w-arduino"
  project_version: "1.0"

# Enable Home Assistant API
api:
  encryption:
    key: !secret masterbedroom2_noise_key
  reboot_timeout: 0s

<<: !include .base-debug.yaml
<<: !include .base.device.light.miboxer-fut-035w-esp32-c3-arduino.yaml
<<: !include .base.global-rgbcct.yaml
<<: !include .base.automation.light-mqtt-1-button.yaml
<<: !include .base.common-sensor-die-temp.yaml
# <<: !include .base.common-binary-sensor.yaml
<<: !include .base.common-sensor.yaml
<<: !include .base.common-button.yaml
<<: !include .base.common-text-sensor.yaml