substitutions:
  name: "masterbedroom2"
  device_ssid: "Master Room 2"
  device_description: "Lumary 18W RGBCW Slim Downlight"
  friendly_name: "Master Bedroom 2"    # Put the name that you want to see in Home Assistant.
  friendly_name_rgb: "Master Bedroom 2 RGB"    # Put the name that you want to see in Home Assistant.
  device_id_white: "masterbedroom2"    # Put the name that you want to see in Home Assistant.
  rgb_device_id: "masterbedroom2rgb" # Put the name that you want to see in Home Assistant.
  switch1b1_topic: masterswitch/button/1/command
  api_key: !secret masterbedroom2_noise_key
  project_name: "lumary.18w-rgbcw-slim-downlight-esp32-c3-esp-idf"
  project_version: "1.0"

<<: !include .base-debug.yaml
<<: !include .base.common-api.yaml
<<: !include .base.device.light.lumary-18w-downlight-esp32-c3-arduino.yaml
<<: !include .base.global-mqtt-automation.yaml
<<: !include .base.automation.light-mqtt-1-button.yaml
<<: !include .base.common-sensor-die-temp.yaml
<<: !include .base.common-button.yaml
<<: !include .base.common-text-sensor.yaml
<<: !include .base.common-binary-sensor.yaml