substitutions:
  name: "bedroom2light4"
  device_ssid: "Bed 2 light 4"
  device_description: "Lumary 9W RGBCW Slim Downlight 4-inch L-SD4B4"
  friendly_name: "Bedroom 2 Light 4"    # Put the name that you want to see in Home Assistant.
  device_name_white: "Bedroom 2 Light 4 White"    # Put the name that you want to see in Home Assistant.
  device_id_white: bedroom2light4white
  device_name_rgb: "Bedroom 2 Light 4 RGB"    # Put the name that you want to see in Home Assistant.
  device_id_rgb: bedroom2light4rgb    # Put the name that you want to see in Home Assistant.
  switch1b1_topic: bedroom2switch2/button/1/command
  switch1b2_topic: bedroom2switch2/button/2/command
  switch1b3_topic: bedroom2switch2/button/3/command
  switch1b4_topic: bedroom2switch2/button/4/command
  light_icon: "hue:light-light-hung"
  light_icon_2: "hue:light-light-hung"
  api_key: !secret bedroom2light4_noise_key
  project_name: "lumary.18w-rgbcw-slim-downlight-l-sd4b4-esp32-c3-wroom-05"
  project_version: "1.0"

packages:
  - !include packages/base/debug.yaml
  - !include packages/devices/light.lumary-9w-downlight-l-sd4b4-esp32-c3-wroom-05.yaml
  - !include packages/common/api.yaml
  - !include packages/global/mqtt-automation.yaml
  - !include packages/automation/light-mqtt-4-button-rgbcct.yaml
  - !include packages/common/binary-sensor.yaml
  - !include packages/common/sensor.yaml
  - !include packages/common/button.yaml
  - !include packages/common/text-sensor.yaml