substitutions:
  device_ssid: "Rashila"
  device_name: rashila
  device_generic_name: "Rashila Light"
  device_main_description: "OffDarks LXD-XGP 28W RGBWW Ceiling LED light located in Rashila Bedroom with discreet Tunable White & RGB Rear Light (shows up as separate lights)."
  device_description: Rashila Light - Main Light
  friendly_name: "Rashila Light - Tunable White"    # Put the name that you want to see in Home Assistant.
  main_device_id: "rashila" # Put the name that you want to see in Home Assistant.
  device_name_rgb: rashilalightrgb
  device_description_rgb: "Rashila Light - RGB."    # Put the name that you want to see in Home Assistant.
  friendly_name_rgb: "Rashila Light RGB"
  frequency_rgb: 100 Hz
  frequency_cw: 1000 Hz
  frequency_ww: 1000 Hz
  switch1b1_topic: masterswitch/button/0/command
  project_name: "offdarks.lxd-xgp-28w-rgbcw-ceiling-light-esp8266-arduino"
  project_version: "1.0"

# Enable Home Assistant API
api:
  password: !secret api_password
  encryption:
    key: !secret rashila_noise_key
  reboot_timeout: 0s

<<: !include .base-debug.yaml
<<: !include .base.light.offdarks-lxd-xgp-28w-ceiling-wemos-d1-mini.yaml
<<: !include .base.global-mqtt-automation.yaml
<<: !include .base.mqtt-light-automation-1-button.yaml
<<: !include .base.sensor-common.yaml
<<: !include .base.text-sensor-common.yaml
<<: !include .base.switch-common.yaml
<<: !include .base.binary-sensor-common.yaml