substitutions:
  name: frontpassage2
  device_ssid: "Front Passage 2"
  device_description: "Lumary 18W RGBCW Slim Downlight"
  friendly_name: "Front Passage 2"    # Put the name that you want to see in Home Assistant.
  friendly_name_rgb: "Front Passage 2 RGB"    # Put the name that you want to see in Home Assistant.
  device_id_white: "frontpassage2"    # Put the name that you want to see in Home Assistant.
  rgb_device_id: "frontpassage2rgb" # Put the name that you want to see in Home Assistant.
  switch1b1_topic: frontswitch/button/2/command
  switch2b1_topic: passageswitch1/button/3/command
  switch2b2_topic: passageswitch1/button/4/command
  switch3b1_topic: stairsswitch1/button/1/command
  switch3b2_topic: stairsswitch1/button/2/command
  api_key: !secret front_passage2_noise_key
  project_name: "lumary.18w-rgbcw-slim-downlight-esp32-c3-esp-idf"
  project_version: "1.0"

packages:
  - !include packages/base/debug.yaml
  - !include packages/devices/light.lumary-18w-downlight-esp32-c3.yaml
  - !include packages/common/api.yaml
  - !include packages/global/mqtt-automation.yaml
  - !include packages/automation/light-mqtt-1-or-2-button-3-switch.yaml
  - !include packages/common/binary-sensor.yaml
  - !include packages/common/button.yaml
  - !include packages/common/sensor-die-temp.yaml
  - !include packages/common/text-sensor.yaml