substitutions:
  name: livingroomlightold
  device_ssid: "Living old"
  device_description: "Ceiling LED light with IR remote located in Ashish Room with discreet Tunable White & RGB Front Light (shows up as separate lights)."
  friendly_name: "Living Room Light old"    # Put the name that you want to see in Home Assistant.
  device_id_white: livingroomlightwhiteold    # Put the name that you want to see in Home Assistant.
  device_name_white: "Living Room Light White Old"
  device_id_rgb: livingroomlightrgb    # Put the name that you want to see in Home Assistant.
  device_name_rgb: "Living Room Light RGB OLd"
  switch1b1_topic: livingswitch/button/1/command
  switch1b2_topic: livingswitch/button/2/command
  switch1b3_topic: livingswitch/button/3/command
  switch1b4_topic: livingswitch/button/4/command
  frequency_rgb: 250 Hz
  frequency_cw: 1000 Hz
  frequency_ww: 1000 Hz
  api_key: !secret living_noise_key
  project_name: "offdarks.lxd-xg68-68w-rgbcw-ceiling-esp32-arduino"
  project_version: "1.0"

packages:
  - !include packages/base/rename.yaml
  - !include packages/devices/light.offdarks-lxd-xg68-68w-esp32.yaml
  - !include packages/common/api.yaml
  - !include packages/global/rgbcct.yaml
  - !include packages/automation/light-mqtt-4-button-rgbcct.yaml
  - !include packages/common/button.yaml
  - !include packages/common/sensor-die-temp.yaml
  - !include packages/common/text-sensor.yaml