substitutions:
  name: frontporch
  device_ssid: "Front Porch"
  device_description: "Lumary 18W RGBCW Slim Downlight"
  friendly_name: "Front Porch"    # Put the name that you want to see in Home Assistant.
  friendly_name_rgb: "Front Porch RGB"    # Put the name that you want to see in Home Assistant.
  device_id_white: "frontporch"    # Put the name that you want to see in Home Assistant.
  rgb_device_id: "frontporchrgb" # Put the name that you want to see in Home Assistant.
  switch1b1_topic: frontswitch/button/3/command
  switch2b1_topic: passageswitch2/button/1/command
  switch2b2_topic: passageswitch2/button/2/command
  api_key: !secret front_porch_noise_key
  project_name: "lumary.18w-rgbcw-slim-downlight-esp32-c3-esp-idf"
  project_version: "1.0"

packages:
  - !include packages/base/debug.yaml
  - !include packages/common/api.yaml
  - !include packages/devices/light.lumary-18w-downlight-esp32-c3.yaml
  - !include packages/global/mqtt-automation.yaml
  - !include packages/automation/light-mqtt-1-button-plus-2-button-switch.yaml
  - !include packages/common/binary-sensor.yaml
  - !include packages/common/button.yaml
  - !include packages/common/sensor-die-temp.yaml
  - !include packages/common/text-sensor.yaml