substitutions:
  name: livingroomlight
  device_ssid: "Living Light"
  device_description: "Ceiling LED light with IR remote located in Ashish Room with discreet Tunable White & RGB Front Light (shows up as separate lights)."
  friendly_name: "Living Room Light"    # Put the name that you want to see in Home Assistant.
  device_id_white: livingroomlightwhite    # Put the name that you want to see in Home Assistant.
  device_name_white: "Living Room Light White"
  device_id_rgb: livingroomlightrgb    # Put the name that you want to see in Home Assistant.
  device_name_rgb: "Living Room Light RGB"
  switch1b1_topic: livingswitch/button/1/command
  switch1b2_topic: livingswitch/button/2/command
  switch1b3_topic: livingswitch/button/3/command
  switch1b4_topic: livingswitch/button/4/command
  frequency_rgb: 250 Hz
  frequency_cw: 1000 Hz
  frequency_ww: 1000 Hz
  api_key: !secret living_noise_key
  project_name: "offdarks.lxd-xg68-68w-rgbcw-ceiling-esp32-arduino"
  project_version: "1.0"

<<: !include .base-debug.yaml
<<: !include .base.common-api.yaml
<<: !include .base.device.light.offdarks-lxd-xg68-68w-ceiling-esp32-arduino.yaml
<<: !include .base.global-rgbcct.yaml
<<: !include .base.automation.light-mqtt-4-button-rgbcct.yaml
<<: !include .base.common-sensor.yaml
<<: !include .base.common-button.yaml
<<: !include .base.common-text-sensor.yaml