substitutions:
  name: lowerloftstairs
  device_ssid: "Lower Loft"
  device_description: "Lumary 18W RGBCW Slim Downlight"
  friendly_name: "Lower Loft Stairs"    # Put the name that you want to see in Home Assistant.
  friendly_name_rgb: "Lower Loft Stairs RGB"    # Put the name that you want to see in Home Assistant.
  device_id_white: "lowerloftstairs"    # Put the name that you want to see in Home Assistant.
  rgb_device_id: "lowerloftstairsrgb" # Put the name that you want to see in Home Assistant.
  switch1b1_topic: loftswitch/button/1/command
  switch1b2_topic: loftswitch/button/2/command
  switch2b1_topic: stairsswitch2/button/1/command
  switch2b2_topic: stairsswitch2/button/2/command 
  api_key: !secret lowerloftstairs_noise_key
  project_name: "lumary.18w-rgbcw-slim-downlight-esp32-c3"
  project_version: "1.0"

packages:
  - !include packages/base/debug.yaml
  - !include packages/common/api.yaml
  - !include packages/devices/light.lumary-18w-downlight-esp32-c3.yaml
  - !include packages/global/mqtt-automation.yaml
  - !include packages/automation/light-mqtt-2-button-2-switch.yaml
  - !include packages/common/binary-sensor.yaml
  - !include packages/common/button.yaml
  - !include packages/common/sensor-die-temp.yaml
  - !include packages/common/text-sensor.yaml