substitutions:
  name: bedroom3
  device_ssid: "Bedroom 3"
  friendly_name: "Bedroom 3" 
  device_description: "OffDarks LXD-XGP 28W RGB-CCT Ceiling LED light ESP32"
  device_name_white: "Bedroom 3 - White"    # Put the name that you want to see in Home Assistant.
  device_id_white: "Bedroom3white"
  device_name_rgb: "Bedroom 3 - RGB"
  device_id_rgb: bedroom3rgb    # Put the name that you want to see in Home Assistant.
  friendly_name_rgb: "Bedroom 3 RGB"
  frequency_rgb: 100 Hz
  frequency_cw: 1000 Hz
  frequency_ww: 1000 Hz
  switch1b1_topic: bedroom3switch/button/1/command
  switch1b2_topic: bedroom3switch/button/2/command
  switch1b3_topic: bedroom3switch/button/3/command
  switch1b4_topic: bedroom3switch/button/4/command
  aqara_remote_b1_topic: zigbee2mqtt/Rashila Stairs/action
  api_key: !secret bedroom3_noise_key
  project_name: "offdarks.lxd-xgp-28w-rgbcw-ceiling-esp32-arduino"
  project_version: "1.0"

packages:
  - !include packages/base/debug.yaml
  - !include packages/devices/light.offdarks-lxd-xgp-28w-esp32.yaml
  - !include packages/global/rgbcct.yaml
  - !include packages/automation/light-mqtt-4-button-rgbcct.yaml
  - !include packages/common/api.yaml
  - !include packages/common/sensor.yaml
  - !include packages/common/button.yaml
  - !include packages/common/text-sensor.yaml
  - !include packages/common/binary-sensor.yaml