substitutions:
  device_ssid: "Bedroom3"
  device_name: bedroom3
  device_description: "ZH United 40W RGBCW Slim Ceiling Light"
  friendly_name: "Bedroom 3"    # Put the name that you want to see in Home Assistant.
  friendly_name_rgb: "Bedroom 3 RGB"    # Put the name that you want to see in Home Assistant.
  main_device_id: "bedroom3"    # Put the name that you want to see in Home Assistant.
  rgb_device_id: "bedroom3rgb" # Put the name that you want to see in Home Assistant.
  # switch1b1_topic: frontswitch/button/4/command
  # switch2b1_topic: passageswitch2/button/3/command
  # switch2b2_topic: passageswitch2/button/4/command
  project_name: "zhunited.40w-rgbcw-slim-ceiling-light-esp32-c3-arduino"
  project_version: "1.0"

# Enable Home Assistant API
api:
  password: !secret api_password
  encryption:
    key: !secret bedroom3_noise_key
  reboot_timeout: 0s

<<: !include .base-debug.yaml
<<: !include .base.light-zhunited-40w-jl-02-ceiling-light-esp32-c3-arduino.yaml
<<: !include .base.global-mqtt-automation.yaml
# <<: !include .base.mqtt-light-automation-1-button-plus-2-button-switch.yaml
# <<: !include .base.sensor-common.yaml
<<: !include .base.sensor-common-die-temp.yaml
<<: !include .base.text-sensor-common.yaml
<<: !include .base.switch-common.yaml
<<: !include .base.binary-sensor-common.yaml