substitutions:
  name: masterbedroom1
  device_ssid: "Master Room 1"
  device_description: "Iralan 42W CCT Slim Ceiling Light ESP32-C3"
  friendly_name: "Master Bedroom 1"
  device_id_white: "masterbedroom1" # Put the name that you want to see in Home Assistant.
  switch1b1_topic: masterswitch/button/2/command
  api_key: !secret masterbedroom1_noise_key
  project_name: "iralan.42w-cwww-slim-ceiling-light-esp32-c3-arduino"
  project_version: "1.0"

packages:
  - !include packages/base/debug.yaml
  - !include packages/devices/light.iralan-42w-anl400yl-esp32-c3.yaml
  - !include packages/global/mqtt-automation.yaml
  - !include packages/automation/light-mqtt-1-button.yaml
  - !include packages/common/api.yaml
  - !include packages/common/binary-sensor.yaml
  - !include packages/common/button.yaml
  - !include packages/common/sensor-die-temp.yaml
  - !include packages/common/text-sensor.yaml