substitutions:
  name: bedroom2
  device_ssid: "Bedroom 2"
  device_description: "MiBoxer WB5 Tuya ESP32-C3 LED Controller."
  friendly_name: "Bedroom 2" # Put the name that you want to see in Home Assistant.
  device_id_white: "bedroom2" # Put the name that you want to see in Home Assistant.
  switch1b1_topic: bedroom2switch1/button/1/command
  switch1b2_topic: bedroom2switch1/button/2/command
  light_icon: "hue:ceiling-aurelle"
  api_key: !secret bedroom2_noise_key
  project_name: "miboxer.wb5-cct-esp32-c3-arduino"
  project_version: "1.0"

packages:
  - !include packages/base/debug.yaml
  - !include packages/devices/light.miboxer-wb5-esp32-c3-bed-2.yaml
  - !include packages/common/api.yaml
  - !include packages/automation/light-mqtt-2-button.yaml
  - !include packages/common/binary-sensor.yaml
  - !include packages/common/sensor-die-temp.yaml
  - !include packages/common/button.yaml
  - !include packages/common/text-sensor.yaml