substitutions:
  device_ssid: "Bedroom 2"
  device_name: bedroom2
  device_description: "MiBoxer WB5 Tuya ESP32-C3 LED Controller."
  friendly_name: "Bedroom 2" # Put the name that you want to see in Home Assistant.
  main_device_id: "bedroom2" # Put the name that you want to see in Home Assistant.
  switch1b1_topic: bedroom2switch1/button/1/command
  switch1b2_topic: bedroom2switch1/button/2/command
  light_icon: "hue:ceiling-aurelle"
  project_name: "miboxer.wb5-cct-esp32-c3-arduino"
  project_version: "1.0"

# Enable Home Assistant API
api:
  encryption:
    key: !secret bedroom2_noise_key
  reboot_timeout: 0s

<<: !include .base-debug.yaml
<<: !include .base.device.light.miboxer-wb5-esp32-c3-arduino.yaml
<<: !include .base.automation.light-mqtt-2-button.yaml
<<: !include .base.common-sensor-die-temp.yaml
# <<: !include .base.common-binary-sensor.yaml
<<: !include .base.common-sensor.yaml
<<: !include .base.common-switch.yaml
<<: !include .base.common-text-sensor.yaml