substitutions:
  name: "miteshspot5"
  device_ssid: "Mit 2 Spot 5"
  device_description: "Athom GU10 RGBCW LB10-5W-ESP-1"
  friendly_name: "Mitesh Spot 5"    # Put the name that you want to see in Home Assistant.
  device_name_white: "Mitesh Spot 5 White"    # Put the name that you want to see in Home Assistant.
  device_id_white: miteshspot5white
  device_name_rgb: "Mitesh Spot 5 RGB"    # Put the name that you want to see in Home Assistant.
  device_id_rgb: miteshspot5rgb    # Put the name that you want to see in Home Assistant.
  switch1b1_topic: miteshswitch2/button/1/command
  switch1b2_topic: miteshswitch2/button/2/command
  switch1b3_topic: miteshswitch2/button/3/command
  switch1b4_topic: miteshswitch2/button/4/command
  light_icon: "hue:bulb-spot-hung"
  light_icon_2: "hue:bulb-spot-hung"
  api_key: !secret miteshbulb5_noise_key
  project_name: "athom.rgbww-light"
  project_version: "1.0"
  # frequency_rgb: 250 Hz
  frequency_cw: 1000 Hz
  frequency_ww: 1000 Hz

packages:
  - !include packages/base/debug.yaml
  - !include packages/devices/bulb.athom-gu10.yaml
  - !include packages/automation/light-mqtt-4-button-rgbcct.yaml
  - !include packages/common/api.yaml
  - !include packages/common/mqtt.yaml
  - !include packages/common/binary-sensor.yaml
  - !include packages/common/button.yaml
  - !include packages/common/sensor-die-temp.yaml
  - !include packages/common/text-sensor.yaml