substitutions:
  name: "bedroom2light1"
  device_ssid: "Bed 2 Light 1"
  device_description: "Lumary 9W RGBCW Slim Downlight 4-inch L-SD4B4"
  friendly_name: "Bedroom 2 Light 1"    # Put the name that you want to see in Home Assistant.
  device_name_white: "Bedroom 2 Light 1 White"    # Put the name that you want to see in Home Assistant.
  device_id_white: bedroom2light1white
  device_name_rgb: "Bedroom 2 Light 1 RGB"    # Put the name that you want to see in Home Assistant.
  device_id_rgb: bedroom2light1rgb    # Put the name that you want to see in Home Assistant.
  switch1b1_topic: bedroom2switch2/button/1/command
  switch1b2_topic: bedroom2switch2/button/2/command
  switch1b3_topic: bedroom2switch2/button/3/command
  switch1b4_topic: bedroom2switch2/button/4/command
  light_icon: "hue:ceiling-aurelle-circle"
  light_icon_2: "hue:ceiling-aurelle-circle"
  project_name: "lumary.18w-rgbcw-slim-downlight-sd4b4-esp32-c3-wroom-05-arduino"
  project_version: "1.0"
  
# Enable Home Assistant API
api:
  encryption:
    key: !secret bedroom2light1_noise_key
  reboot_timeout: 0s

<<: !include .base-debug.yaml
<<: !include .base.device.light.lumary-9w-downlight-l-sd4b4-esp32-c3-wroom-05-arduino.yaml
# <<: !include .base.automation.light-mqtt-secure-4-button-rgbcct-esp8266.yaml
<<: !include .base.global-mqtt-automation.yaml
<<: !include .base.automation.light-mqtt-4-button-rgbcct.yaml
<<: !include .base.common-binary-sensor.yaml
<<: !include .base.common-sensor.yaml
<<: !include .base.common-button.yaml
<<: !include .base.common-text-sensor.yaml