substitutions:
  name: "kitchencounter2"
  device_ssid: "Kitchen C 2"
  device_description: "MiBoxer FUT035W Tuya ESP32-C3 LED Controller."
  friendly_name: "Kitchen Counter 2" # Put the name that you want to see in Home Assistant.
  device_id_white: "kitchencounter2" # Put the name that you want to see in Home Assistant.
  light_icon: "hue:lightstrip"
  api_key: !secret kitchencounter2_noise_key
  project_name: "miboxer.fut035w-arduino"
  project_version: "1.0"

packages:
  - !include packages/base/debug-tuya.yaml
  - !include packages/devices/light.miboxer-fut-035w-esp32-c3.yaml
  - !include packages/common/api.yaml
  - !include packages/common/binary-sensor.yaml
  - !include packages/common/button.yaml
  - !include packages/common/sensor-die-temp.yaml
  - !include packages/common/text-sensor.yaml