substitutions:
  device_ssid: "Bathroom Light"
  device_name: bathroomlight
  device_description: "CWWW 36W Starry PMMA Square Ceiling LED light"
  friendly_name: "Bathroom Light"    # Put the name that you want to see in Home Assistant.
  main_device_id: "bathroomlight"    # Put the name that you want to see in Home Assistant.
  tradfri_topic: ashishswitch-/button/1/command
  project_name: "lusunt.36w-cct-starry-pmmma-ceiling-light-square-esp-12f"
  project_version: "1.0"

# Enable Home Assistant API
api:
  password: !secret api_password
  encryption:
    key: !secret bathroom_noise_key
  reboot_timeout: 0s

<<: !include .base-debug.yaml
<<: !include .base.light-lusunt-26w-esp12f.yaml
<<: !include .base.mqtt-light-automation-tradfri.yaml
<<: !include .base.sensor-common.yaml
<<: !include .base.text-sensor-common.yaml
<<: !include .base.switch-common.yaml
<<: !include .base.binary-sensor-common.yaml