substitutions:
  device_ssid: "Master Room 1"
  device_name: masterbedroom1
  device_description: "Iralan 42W CCT Slim Ceiling Light ESP32-C3"
  friendly_name: "Master Bedroom 1"
  main_device_id: "masterbedroom1" # Put the name that you want to see in Home Assistant.
  switch1b1_topic: masterswitch/button/2/command
  project_name: "iralan.42w-cwww-slim-ceiling-light-esp32-c3-arduino"
  project_version: "1.0"

# Enable Home Assistant API
api:
  password: !secret api_password
  encryption:
    key: !secret masterbedroom1_noise_key
  reboot_timeout: 0s

<<: !include .base-debug.yaml
<<: !include .base.light-iralan-42w-anl400yl-esp32-c3-arduino.yaml
<<: !include .base.mqtt-light-automation-1-button.yaml
<<: !include .base.sensor-common-die-temp.yaml
<<: !include .base.text-sensor-common.yaml
<<: !include .base.switch-common.yaml
<<: !include .base.binary-sensor-common.yaml