substitutions:
  name: "masterbedroom2"
  device_ssid: "Master Room 2"
  device_description: "Lumary 18W RGBCW Slim Downlight"
  friendly_name: "Master Bedroom 2"    # Put the name that you want to see in Home Assistant.
  friendly_name_rgb: "Master Bedroom 2 RGB"    # Put the name that you want to see in Home Assistant.
  device_id_white: "masterbedroom2"    # Put the name that you want to see in Home Assistant.
  rgb_device_id: "masterbedroom2rgb" # Put the name that you want to see in Home Assistant.
  switch1b1_topic: masterswitch/button/1/command
  api_key: !secret masterbedroom2_noise_key
  project_name: "lumary.18w-rgbcw-slim-downlight-esp32-c3-esp-idf"
  project_version: "1.0"

packages:
  - !include packages/base/debug.yaml
  - !include packages/devices/lumary-18w-downlight-esp32-c3.yaml
  - !include packages/global/mqtt-automation.yaml
  - !include packages/automation/light-mqtt-1-button.yaml
  - !include packages/common/api.yaml
  - !include packages/common/binary-sensor.yaml
  - !include packages/common/button.yaml
  - !include packages/common/sensor-die-temp.yaml
  - !include packages/common/text-sensor.yaml