substitutions:
  device_ssid: "Front Passage 1"
  device_name: frontpassage1
  device_description: "Lumary 18W RGBCW Slim Downlight"
  friendly_name: "Front Passage 1"    # Put the name that you want to see in Home Assistant.
  friendly_name_rgb: "Front Passage 1 RGB"    # Put the name that you want to see in Home Assistant.
  main_device_id: "frontpassage1"    # Put the name that you want to see in Home Assistant.
  rgb_device_id: "frontpassage1rgb" # Put the name that you want to see in Home Assistant.
  switch1b1_topic: frontswitch/button/2/command
  switch2b1_topic: passageswitch1/button/3/command
  switch2b2_topic: passageswitch1/button/4/command
  switch3b1_topic: stairsswitch1/button/1/command
  switch3b2_topic: stairsswitch1/button/2/command
  project_name: "lumary.18w-rgbcw-slim-downlight-esp32-c3-esp-idf"
  project_version: "1.0"

# Enable Home Assistant API
api:
  password: !secret api_password
  encryption:
    key: !secret front_passage1_noise_key
  reboot_timeout: 0s

<<: !include .base-debug.yaml
<<: !include .base.device.light.lumary-18w-downlight-esp32-c3-arduino.yaml
<<: !include .base.global-mqtt-automation.yaml
<<: !include .base.automation.light-mqtt-1-or-2-button-3-switch.yaml
<<: !include .base.common-binary-sensor.yaml
<<: !include .base.common-sensor.yaml
<<: !include .base.common-switch.yaml
<<: !include .base.common-text-sensor.yaml