substitutions:
  name: stairs
  device_ssid: "Stairs"
  device_description: "Iralan 42W CCT Slim Ceiling Light ESP32-S2"
  friendly_name: "Stairs"
  device_id_white: "stairs" # Put the name that you want to see in Home Assistant.
  switch1b1_topic: frontswitch/button/1/command
  switch2b1_topic: passageswitch1/button/1/command
  switch2b2_topic: passageswitch1/button/2/command
  switch3b1_topic: stairsswitch1/button/3/command
  switch3b2_topic: stairsswitch1/button/4/command
  aqara_remote_b2_topic: zigbee2mqtt/Rashila Stairs/action
  longitude: !secret longitude
  latitude: !secret latitude
  presence_sensor_mqtt_topic: stairssensor/binary_sensor/stairs_sensor_presence_state/state
  api_key: !secret stairs_noise_key
  project_name: "iralan.42w-cwww-slim-ceiling-light-esp32-s2-arduino"
  project_version: "1.0"

packages:
  - !include packages/base/debug.yaml
  - !include packages/devices/light.iralan-42w-anl400yl-esp32-s2.yaml
  - !include packages/global/mqtt-automation.yaml
  - !include packages/automation/light-mqtt-1-or-2-button-4-switch-plus-zigbee2mqtt.yaml
  - !include packages/automation/light-udp-mmwave.yaml
  - !include packages/common/api.yaml
  - !include packages/common/binary-sensor.yaml
  - !include packages/common/button.yaml
  - !include packages/common/sensor-die-temp.yaml
  - !include packages/common/text-sensor.yaml