substitutions:
  device_ssid: "Lower Loft Dev"
  device_name: lowerloftstairs-dev
  device_description: "Lumary 18W RGBCW Slim Downlight Dev"
  friendly_name: "Lower Loft Stairs Dev"    # Put the name that you want to see in Home Assistant.
  friendly_name_rgb: "Lower Loft Stairs Dev RGB"    # Put the name that you want to see in Home Assistant.
  main_device_id: "lowerloftstairsdev"    # Put the name that you want to see in Home Assistant.
  rgb_device_id: "lowerloftstairsdevrgb" # Put the name that you want to see in Home Assistant.
  switch1b1_topic: loftswitchdev/button/1/command
  switch1b2_topic: loftswitchdev/button/2/command
  switch2b1_topic: stairsswitch2dev/button/1/command
  switch2b2_topic: stairsswitch2dev/button/2/command
  project_name: "lumary.18w-rgbcw-slim-downlight-esp32-c3-arduino-dev"
  project_version: "1.0"

# Enable Home Assistant API
api:
  password: !secret api_password
  encryption:
    key: !secret lowerloftstairs_noise_key
  reboot_timeout: 0s

<<: !include .base-debug-dev.yaml
<<: !include .base.light-lumary-18w-downlight-esp32-c3-dev.yaml
<<: !include .base.global-mqtt-automation.yaml
<<: !include .base.mqtt-light-automation-2-button-2-switch.yaml
<<: !include .base.sensor-common-die-temp.yaml
<<: !include .base.text-sensor-common.yaml
<<: !include .base.switch-common.yaml
<<: !include .base.binary-sensor-common.yaml