substitutions:
  name: bathroom
  device_ssid: "Bathroom"
  device_description: "ZH United 40W RGBCW Slim Ceiling Light"
  friendly_name: "Bathroom"    # Put the name that you want to see in Home Assistant.
  friendly_name_rgb: "Bathroom RGB"    # Put the name that you want to see in Home Assistant.
  device_id_white: "bathroom"    # Put the name that you want to see in Home Assistant.
  rgb_device_id: "bathroomrgb" # Put the name that you want to see in Home Assistant.
  switch1_topic: bathroomrelay/button/1/command
  ikea_tradfri_topic: zigbee2mqtt/Bathroom Remote/action
  api_key: !secret bathroom_noise_key
  project_name: "zhunited.40w-rgbcw-slim-ceiling-light-esp32-c3-arduino"
  project_version: "1.0"

<<: !include .base-debug.yaml
<<: !include .base.device.light.zhunited-40w-jl-02-ceiling-light-esp32-c3-arduino.yaml
<<: !include .base.common-api.yaml
<<: !include .base.global-mqtt-automation.yaml
<<: !include .base.automation.light-mqtt-bathroom.yaml
<<: !include .base.common-sensor-die-temp.yaml
<<: !include .base.common-button.yaml
<<: !include .base.common-text-sensor.yaml
<<: !include .base.common-binary-sensor.yaml