substitutions:
  device_ssid: "Stairs"
  device_name: stairs
  device_description: "Iralan 42W CCT Slim Ceiling Light ESP32-S2"
  friendly_name: "Stairs"
  main_device_id: "stairs" # Put the name that you want to see in Home Assistant.
  switch1b1_topic: frontswitch/button/1/command
  switch2b1_topic: passageswitch1/button/1/command
  switch2b2_topic: passageswitch1/button/2/command
  switch3b1_topic: stairsswitch1/button/3/command
  switch3b2_topic: stairsswitch1/button/4/command
  aqara_topic: stairsswitch1/button/4/command
  project_name: "iralan.42w-cwww-slim-ceiling-light-esp32-s2-arduino"
  project_version: "1.0"

# Enable Home Assistant API
api:
  password: !secret api_password
  encryption:
    key: !secret stairs_noise_key
  reboot_timeout: 0s

<<: !include .base-debug.yaml
<<: !include .base.light-iralan-42w-anl400yl-esp32-s2-arduino.yaml
<<: !include .base.global-mqtt-automation.yaml
<<: !include .base.mqtt-light-automation-1-or-2-button-3-switch.yaml
<<: !include .base.sensor-common-die-temp.yaml
<<: !include .base.text-sensor-common.yaml
<<: !include .base.switch-common.yaml
<<: !include .base.binary-sensor-common.yaml