substitutions:
  name: "tuya-sparelight"
  device_ssid: "Tuya-Spare"
  device_description: "Tuya 72W RGBCCT Retrofit ESP32-C3"
  friendly_name: "Tuya Spare"    # Put the name that you want to see in Home Assistant.
  friendly_name_rgb: "Tuya Spare RGB"    # Put the name that you want to see in Home Assistant.
  device_id_white: "tuya_spare"    # Put the name that you want to see in Home Assistant.
  rgb_device_id: "tuya_sparergb" # Put the name that you want to see in Home Assistant.
  # switch1b1_topic: bedroom2switch2/button/1/command
  # switch1b2_topic: bedroom2switch2/button/2/command
  # switch1b3_topic: bedroom2switch2/button/3/command
  # switch1b4_topic: bedroom2switch2/button/4/command
  light_icon: "hue:ceiling-aurelle-circle"
  light_icon_2: "hue:ceiling-aurelle-circle"
  api_key: !secret tuyaspare_noise_key
  project_name: "tuya.72w-rgbcw-retrofit-esp32-c3"
  project_version: "1.0"

packages:
  - !include packages/base/debug.yaml
  - !include packages/devices/light.tuya-72w-rgbcw-panel-esp32-c3.yaml
  - !include packages/common/api.yaml
  - !include packages/global/mqtt-automation.yaml
  # - !include packages/automation/light-mqtt-4-button-rgbcct.yaml
  - !include packages/common/binary-sensor.yaml
  - !include packages/common/sensor.yaml
  - !include packages/common/button.yaml
  - !include packages/common/text-sensor.yaml