substitutions:
  name: "miteshspot3"
  device_ssid: "Mit Spot 3"
  device_description: "Athom GU10 RGBCW LB10-5W-ESP-1"
  friendly_name: "Mitesh Spot 3"    # Put the name that you want to see in Home Assistant.
  device_name_white: "Mitesh Spot 3 White"    # Put the name that you want to see in Home Assistant.
  device_id_white: miteshspot3white
  device_name_rgb: "Mitesh Spot 3 RGB"    # Put the name that you want to see in Home Assistant.
  device_id_rgb: miteshspot3rgb    # Put the name that you want to see in Home Assistant.
  switch1b1_topic: miteshswitch/button/1/command
  switch1b2_topic: miteshswitch/button/2/command
  switch1b3_topic: miteshswitch/button/3/command
  switch1b4_topic: miteshswitch/button/4/command
  light_icon: "hue:bulb-spot-hung"
  light_icon_2: "hue:bulb-spot-hung"
  project_name: "athom.rgbww-light"
  project_version: "1.0"
  # frequency_rgb: 250 Hz
  frequency_cw: 1000 Hz
  frequency_ww: 1000 Hz
  
# Enable Home Assistant API
api:
  encryption:
    key: !secret miteshbulb3_noise_key
  reboot_timeout: 0s

<<: !include .base-debug.yaml
<<: !include .base.device.bulb.athom-gu10.yaml
<<: !include .base.automation.light-mqtt-4-button-rgbcct.yaml
<<: !include .base.common-binary-sensor.yaml
<<: !include .base.common-sensor.yaml
<<: !include .base.common-button.yaml
<<: !include .base.common-text-sensor.yaml
      