substitutions:
  name: "bedroom2thread"
  device_ssid: "Bed 2 Thread"
  device_description: "Espressif ESP32-C6 DevKit Used as Thread Router"
  friendly_name: "Bedroom 2 OpenThread" # Put the name that you want to see in Home Assistant.
  api_key: !secret bedroom2thread_new_noise_key
  project_name: "espressif.esp32-c6-openthread"
  project_version: "1.0"

packages:
  - !include packages/base/debug-thread.yaml
  - !include packages/devices/radio.esp32-c6-openthread.yaml
  - !include packages/common/api.yaml
  - !include packages/common/binary-sensor.yaml
  - !include packages/common/button.yaml
  - !include packages/common/sensor-thread.yaml
  - !include packages/common/text-sensor-thread.yaml