substitutions:
  name: "bedroom2zigbee"
  device_ssid: "Bed 2 Zigbee"
  device_description: "Epressif ESP32-C6 DevKit Used as Thread Router"
  friendly_name: "Bedroom 2 Zigbee Router" # Put the name that you want to see in Home Assistant.
  api_key: !secret bedroom3thread_new_noise_key
  project_name: "espressif.esp32-c6-zigbee"
  project_version: "1.0"

packages:
  - !include packages/base/debug-c6.yaml
  - !include packages/devices/radio.esp32-c6-zigbee.yaml
  - !include packages/common/api.yaml
  - !include packages/common/binary-sensor.yaml
  - !include packages/common/button.yaml
  - !include packages/common/sensor-thread.yaml
  - !include packages/common/text-sensor-thread.yaml