substitutions:
  device_ssid: "Bath Entrance"
  device_name: bathentrancerelay
  device_main_description: "Shelly 1 Exposed as light"
  device_description: Bath Entrance Light
  friendly_name: "Bath Entrance" # Put the name that you want to see in Home Assistant.
  main_device_id: "bathentrancerelay"    # Put the name that you want to see in Home Assistant.
  lonsonho1_topic: ashishswitch2/button/1/command
  light_icon: "hue:bulb-spot-hung"
  project_name: "shelly.shelly1-relay-light"
  project_version: "1.0"

# Enable Home Assistant API
api:
  password: !secret api_password
  encryption:
    key: !secret bathentrancerelay_noise_key
  reboot_timeout: 0s

<<: !include .base-debug.yaml
<<: !include .base.relay.shelly-1-light.yaml
<<: !include .base.mqtt-light-automation-1-lonsonho.yaml
<<: !include .base.sensor-common.yaml
<<: !include .base.text-sensor-common.yaml
<<: !include .base.switch-common.yaml
<<: !include .base.binary-sensor-shelly-1-edge-switch.yaml