substitutions:
  name: bathentrancerelay
  device_ssid: "Bath Entrance"
  device_main_description: "Shelly Plus 2 PM Exposed as Light"
  device_description: Bath Entrance Light with Power Monitoring
  friendly_name: "Bath Entrance" # Put the name that you want to see in Home Assistant.
  device_id: "bathentrancerelay"    # Put the name that you want to see in Home Assistant.
  lonsonho_single_topic: zigbee2mqtt/Bath & Toilet Hallway/action
  light_icon: "hue:bulb-spot-hung"
  # Higher value gives lower watt readout
  current_res: "0.001"
  # Lower value gives lower voltage readout
  voltage_div: "1925"
  # light_icon: "hue:bulb-spot-hung"
  api_key: !secret bathentrancerelay_noise_key
  project_name: "shelly.shellyplus1pm-relay"
  project_version: "1.0"

packages:
  - !include packages/base/debug.yaml
  - !include packages/devices/relay.shelly-plus-1pm-solo-light.yaml
  - !include packages/automation/light-mqtt-1-lonsonho.yaml
  - !include packages/common/api.yaml
  - !include packages/common/button.yaml
  - !include packages/common/text-sensor.yaml
  - !include packages/binary-sensor/shelly-plus-1pm-edge-switch.yaml
  - !include packages/sensor/shelly-plus-1pm-light.yaml