substitutions:
  device_ssid: "Bathroom Relay"
  device_name: bathroomrelay
  device_main_description: "Shelly 2.5 Bathroom Relay Exposed as Fan with MQTT Switch"
  device_description: Bathroom Relay
  friendly_name: "Bathroom" # Put the name that you want to see in Home Assistant.
  main_device_id: "bathroomrelay"    # Put the name that you want to see in Home Assistant.
  lonsonho_topic: ashishswitch2/button/1/command
  project_name: "shelly.shelly25-relay-light-fan"
  project_version: "1.0"

# Enable Home Assistant API
api:
  password: !secret api_password
  encryption:
    key: !secret bathroomrelay_noise_key
  reboot_timeout: 0s

<<: !include .base-debug.yaml
<<: !include .base.relay.shelly-2.5-bathroom.yaml
<<: !include .base.mqtt-light-automation-1-dual-lonsonho.yaml
<<: !include .base.sensor-shelly2.5.yaml
<<: !include .base.text-sensor-common.yaml
<<: !include .base.switch-common.yaml
<<: !include .base.binary-sensor-shelly-2.5-edge-switch-detached-fallback.yaml