substitutions:
  name: chime
  device_ssid: "ShellyChime"
  device_main_description: "Shelly Plus 1 PM Relay Chime"
  device_description: Shelly Plus 1 PM Relay Chime
  friendly_name: "Chime" # Put the name that you want to see in Home Assistant.
  device_id_white: "shellyplus1pmchime"
  # Higher value gives lower watt readout
  current_res: "0.001"
  # Lower value gives lower voltage readout
  voltage_div: "1925"
  chime_icon: "mdi:bell-ring"
  project_name: "shelly.shellyplus1pm-relay-chime-arduino"
  project_version: "1.0"

# Enable Home Assistant API
api:
  encryption:
    key: !secret chime_noise_key
  reboot_timeout: 0s

packages:
  - !include packages/base/debug.yaml
  - !include packages/devices/relay.shelly-plus-1pm-solo-chime.yaml
  - !include packages/automation/light-mqtt-2-lonsonho-toilet.yaml
  - !include packages/common/api.yaml
  - !include packages/common/mqtt.yaml
  - !include packages/common/button.yaml
  - !include packages/common/text-sensor.yaml
  - !include packages/binary-sensor/shelly-plus-1pm-chime-trigger.yaml
  - !include packages/sensor/shelly-plus-1pm.yaml
  - !include packages/switch/shelly-plus-1pm-chime.yaml