substitutions:
  name: toiletrelay
  device_ssid: "Toilet Relay"
  device_main_description: "Shelly 2.5 Toilet Relay Exposed as Light & Fan"
  device_description: Toilet Relay
  friendly_name: "Toilet" # Put the name that you want to see in Home Assistant.
  device_id: "toiletrelay"    # Put the name that you want to see in Home Assistant.
  relay_1: "Toilet"
  relay_2: "Toilet Extractor"
  # Relay trip limits
  max_power: "3600.0"
  max_temp: "80.0"
  # light_icon: "hue:bulb-spot-hung"
  lonsonho_dual_topic: zigbee2mqtt/Toilet Wall/action
  light_icon: "hue:bulb-spot-hung"
  api_key: !secret toiletrelay_noise_key
  project_name: "shelly.shellyplus2pm-relay-light-fan"
  project_version: "1.0"

packages:
  - !include packages/base/debug.yaml
  - !include packages/devices/relay.shelly-plus-2pm-toilet.yaml
  - !include packages/automation/light-mqtt-2-lonsonho-toilet.yaml
  - !include packages/common/api.yaml
  - !include packages/common/mqtt.yaml
  - !include packages/common/button.yaml
  - !include packages/common/text-sensor.yaml
  - !include packages/binary-sensor/shelly-plus-2pm-toilet-fallback.yaml
  - !include packages/sensor/shelly-plus-2pm-toilet.yaml
