substitutions:
  name: toiletrelay
  device_ssid: "Toilet Relay"
  device_main_description: "Shelly 2.5 Toilet Relay Exposed as Light & Fan"
  device_description: Toilet Relay
  friendly_name: "Toilet" # Put the name that you want to see in Home Assistant.
  device_id: "toiletrelay"    # Put the name that you want to see in Home Assistant.
  relay_1: "Toilet"
  relay_2: "Toilet"
  # Relay trip limits
  max_power: "3600.0"
  max_temp: "80.0"
  # light_icon: "hue:bulb-spot-hung"
  lonsonho_dual_topic: zigbee2mqtt/Toilet Wall/action
  light_icon: "hue:bulb-spot-hung"
  project_name: "shelly.shellyplus2pm-relay-light-fan"
  project_version: "1.0"

# Enable Home Assistant API
api:
  encryption:
    key: !secret toiletrelay_noise_key
  reboot_timeout: 0s

<<: !include .base-debug.yaml
<<: !include .base.device.relay.shelly-plus-2pm-toilet-arduino.yaml
<<: !include .base.automation.light-mqtt-2-lonsonho-toilet.yaml
<<: !include .base.sensor-shelly-plus-2pm-toilet.yaml
<<: !include .base.common-button.yaml
<<: !include .base.common-text-sensor.yaml
<<: !include .base.binary-sensor-shelly-plus-2pm-toilet-fallback.yaml
