substitutions:
  name: bathroomrelay
  device_ssid: "Bathr'm Relay"
  device_main_description: "Shelly Plus 2PM Bathroom Relay Exposed as Fan with MQTT Switch"
  device_description: Bathroom Relay
  friendly_name: "Bathroom" # Put the name that you want to see in Home Assistant.
  device_id: "bathroomrelay"    # Put the name that you want to see in Home Assistant.
  relay_1: "Relay 1"
  relay_2: "Bathroom"
  # Relay trip limits
  max_power: "3600.0"
  max_temp: "80.0"
  # light_icon: "hue:bulb-spot-hung"
  lonsonho_dual_topic: zigbee2mqtt/Bathroom Wall Remote/action
  project_name: "shelly.shellyplus2pm-relay-light-fan"
  project_version: "1.0"

# Enable Home Assistant API
api:
  encryption:
    key: !secret bathroomrelay_noise_key
  reboot_timeout: 0s

packages:
  - !include packages/base/debug.yaml
  - !include packages/devices/relay.shelly-plus-2pm-bathroom.yaml
  - !include packages/automation/light-mqtt-2-lonsonho-bath-fan.yaml
  - !include packages/common/api.yaml
  - !include packages/common/mqtt.yaml
  - !include packages/common/button.yaml
  - !include packages/common/text-sensor.yaml
  - !include packages/binary-sensor/shelly-plus-2pm-bathroom-fallback.yaml
  - !include packages/sensor/shelly-plus-2pm-bathroom.yaml