substitutions:
  name: storesensor
  device_ssid: "Store Sensor"
  device_description: "Reed Switch Sensor ESP32 AC Relay Board Arduino"
  friendly_name: "Store" # Put the name that you want to see in Home Assistant.
  sensor_name: "Store Room Door"
  sensor_icon: "mdi:door"
  sensor_class: "door"
  presence_binary_sensor_id: storeroompresence
  light_command_topic_1: store/light/store/command
  udp_consumer_device_name_1: store
  udp_consumer_key_1: !secret udp_key_1
  udp_provider_key_1: !secret udp_key_2
  api_key: !secret storesensor_noise_key
  project_name: "diy.ac_relay-board-reed-switch-esp32-arduino"
  project_version: "1.0"

packages:
- !include packages/base/debug.yaml
- !include packages/devices/sensor.reed-switch-esp32.yaml
- !include packages/common/api.yaml
- !include packages/common/mqtt.yaml
- !include packages/common/sensor-die-temp.yaml
- !include packages/common/button.yaml
- !include packages/common/text-sensor.yaml
- !include packages/binary-sensor/reed-switch-store.yaml
- !include packages/switch/reed-switch-store.yaml
- !include packages/udp/prescence-sensor-zy-m100.yaml