substitutions:
  name: frontentrancesensor
  device_ssid: "Front Motion"
  device_description: "Tuya ZY-M100 Motion Sensor ESP32-C3 Arduino"
  friendly_name: "Front Entrance Sensor" # Put the name that you want to see in Home Assistant.
  # switch1b1_topic: ashishswitch1/button/1/command
  # switch1b2_topic: ashishswitch1/button/2/command
  presence_binary_sensor_id: frontentrancepresence
  light_command_topic_1: frontentrance/light/frontentrance/command
  light_command_topic_2: frontporch/light/porch/command
  udp_consumer_device_name_1: frontentrancesensor
  udp_consumer_key_1: !secret udp_key_1
  udp_provider_key_1: !secret udp_key_2
  sensor_icon: "hue:ceiling-aurelle"
  api_key: !secret frontentrancemotion_noise_key
  project_name: "tuya.zy-m100-wifi"
  project_version: "1.0"

packages:
  - !include packages/base/debug-tuya.yaml
  - !include packages/devices/sensor.zy-m100-esp32-c3.yaml
  - !include packages/common/api.yaml
  - !include packages/common/mqtt.yaml
  - !include packages/common/button.yaml
  - !include packages/common/text-sensor.yaml
  - !include packages/sensor/zy-m100.yaml
  - !include packages/binary-sensor/zy-m100.yaml