substitutions:
  name: frontentrancesensor
  device_ssid: "Front Motion"
  device_description: "Tuya ZY-M100 Motion Sensor ESP32-C3 Arduino"
  friendly_name: "Front Entrance Sensor" # Put the name that you want to see in Home Assistant.
  # switch1b1_topic: ashishswitch1/button/1/command
  # switch1b2_topic: ashishswitch1/button/2/command
  presence_binary_sensor_id: storeroompresence
  light_command_topic: store/light/store/command
  udp_consumer_device_name_1: store
  udp_consumer_key_1: !secret udp_key_1
  udp_provider_key_1: !secret udp_key_2
  sensor_icon: "hue:ceiling-aurelle"
  api_key: !secret frontentrancemotion_noise_key
  project_name: "tuya.zy-m100-wifi"
  project_version: "1.0"

<<: !include .base-debug-tuya.yaml
<<: !include .base.device.sensor.zy-m100-esp32-c3-arduino.yaml
<<: !include .base.common-api.yaml
<<: !include .base.binary-sensor-zy-m100.yaml
<<: !include .base.sensor-zy-m100.yaml
<<: !include .base.common-mqtt.yaml
<<: !include .base.common-button.yaml
<<: !include .base.common-text-sensor.yaml
# <<: !include .base.text-sensor-zy-m100.yaml