substitutions:
  name: bathroomsensor
  device_ssid: "Bathroom Sensor"
  device_description: "BME680 Sensor ESP32 AC Relay Board Arduino"
  friendly_name: "Bathroom" # Put the name that you want to see in Home Assistant.
  # switch1b1_topic: ashishswitch1/button/1/command
  # switch1b2_topic: ashishswitch1/button/2/command
  sensor_icon: "hue:ceiling-aurelle"
  api_key: !secret bathroomsensor_noise_key
  project_name: "diy.ac_relay_board_bme680-bsec-esp32-arduino"
  project_version: "1.0"

packages:
  - !include packages/base/debug.yaml
  - !include packages/devices/sensor-bme680-bsec-esp32.yaml
  - !include packages/common/api.yaml
  - !include packages/common/mqtt.yaml
  - !include packages/common/binary-sensor.yaml
  - !include packages/common/button.yaml
  - !include packages/sensor/bme680-bsec.yaml
  - !include packages/text-sensor/bme680-bsec.yaml