substitutions:
  device_ssid: "esp32dal"
  device_name: esp32onewirebus
  device_main_description: "esp32 onewirebus dallas test"
  device_description: esp32 onewirebus dallas test
  friendly_name: "ESP32 onewirebus  Test" # Put the name that you want to see in Home Assistant.
  main_device_id: "esp32onewirebustest"    # Put the name that you want to see in Home Assistant.
  project_name: "esp32.1-wire-owbd-arduino"
  project_version: "1.0"

# Enable Home Assistant API
api:
  encryption:
    key: !secret esp32_dallas_noise_key
  reboot_timeout: 0s

<<: !include .base-debug-verbose.yaml
<<: !include .base.device.sensor.esp32-1-wire-new-arduino.yaml
# <<: !include .base.automation.light-mqtt-1-lonsonho.yaml
# <<: !include .base.common-sensor.yaml
<<: !include .base.sensor-esp32-onewire.yaml
<<: !include .base.common-button.yaml
<<: !include .base.common-text-sensor.yaml