substitutions:
  device_ssid: "BME280 1-Wire"
  device_name: bme2801wire
  device_description: "BME-280 1-Wire Sensor Powered by ESP32"
  friendly_name: "BME280 1-Wire"
  main_device_id: bme2801wire # Put the name that you want to see in Home Assistant.
  project_name: "diy.bme2801wire-esp32-esp-idf"
  project_version: "1.0"

<<: !include .base-debug.yaml
# <<: !include .base.device.sensor-bme280-esp32-alternate-esp-idf.yaml
# <<: !include .base.device.sensor-bme280-shelly-dallas-esp32-esp-idf.yaml
# <<: !include .base.device.sensor-bme280-shelly-dallas-esp32-arduino.yaml
<<: !include .base.device.sensor-bme280-1-wire-esp32-arduino.yaml

# Enable Home Assistant API
api:
  encryption:
    key: !secret testtemp_noise_key
  reboot_timeout: 0s

# <<: !include .base.common-mqtt.yaml
<<: !include .base.sensor-bme280-1-wire.yaml
<<: !include .base.common-switch.yaml
<<: !include .base.common-text-sensor.yaml