substitutions:
  device_ssid: "Master Switch"
  device_name: masterswitch
  device_description: "Shelly Plus i4 Switch Module"
  friendly_name: "Master Switch"
  main_device_id: "masterbedroomswitch" # Put the name that you want to see in Home Assistant.
  project_name: "shelly.plusi4-esp32-solo-arduino"
  project_version: "1.0"

<<: !include .base-debug.yaml
<<: !include .base.device.switch.shelly-plus-i4-arduino.yaml

# Enable Home Assistant API
api:
  encryption:
    key: !secret masterswitch_noise_key
  reboot_timeout: 0s

<<: !include .base.common-mqtt.yaml
<<: !include .base.common-sensor-die-temp.yaml
<<: !include .base.common-button.yaml
<<: !include .base.common-text-sensor.yaml
<<: !include .base.binary-sensor-shelly-i4-2-buttons-fallback.yaml