substitutions:
  name: diningswitch
  device_ssid: "Dining Switch"
  device_description: "Shelly Plus i4 Switch Module"
  friendly_name: "Dining Switch"
  api_key: !secret diningswitch_noise_key
  project_name: "shelly.plusi4-esp32c3-8mb-arduino"
  project_version: "1.0"

packages:
  - !include packages/base/debug.yaml
  - !include packages/devices/switch.shelly-plus-i4-gen3.yaml
  - !include packages/common/api.yaml
  - !include packages/common/mqtt.yaml
  # - !include packages/common/sensor-die-temp.yaml
  - !include packages/common/button.yaml
  - !include packages/common/text-sensor.yaml
  - !include packages/binary-sensor/shelly-i4-gen3-4-buttons-fallback.yaml