substitutions:
  name: passageswitch2
  device_ssid: "Passage 2"
  device_description: "Shelly Plus i4 Switch Module"
  friendly_name: "Passage Switch 2"
  api_key: !secret passageswitch2_noise_key
  project_name: "shelly.plusi4-esp32-solo-arduino"
  project_version: "1.0"

<<: !include .base-debug.yaml
<<: !include .base.device.switch.shelly-plus-i4-arduino.yaml

<<: !include .base.common-mqtt.yaml
<<: !include .base.common-sensor-die-temp.yaml
<<: !include .base.common-api.yaml
<<: !include .base.common-button.yaml
<<: !include .base.common-text-sensor.yaml
<<: !include .base.binary-sensor-shelly-i4-4-buttons-fallback.yaml