substitutions:
  device_ssid: "Bed 2 Switch 2"
  device_name: bedroom2switch2
  device_description: "Shelly Plus i4 Switch Module"
  friendly_name: "Bedroom 2 Switch 2"
  main_device_id: "bedroom2switch2" # Put the name that you want to see in Home Assistant.
  remote_node: bedroom2spot1.local
  remote_light_id: bedroom2spot1
  project_name: "shelly.plusi4-esp32-solo-arduino"
  project_version: "1.0"

<<: !include .base-debug.yaml
# <<: !include .base.device.switch.shelly-plus-i4-arduino.yaml
<<: !include .base.device.switch.shelly-plus-i4-testing.yaml

# Enable Home Assistant API
api:
  password: !secret api_password
  encryption:
    key: !secret bedroom2switch2_noise_key
  reboot_timeout: 0s

<<: !include .base.common-mqtt.yaml
<<: !include .base.common-sensor-die-temp.yaml
<<: !include .base.common-switch.yaml
<<: !include .base.common-text-sensor.yaml
<<: !include .base.binary-sensor-shelly-i4-4-buttons-testing.yaml
<<: !include .base.button-testing-internal.yaml