substitutions:
  name: passageswitch2
  device_ssid: "Passage 2"
  device_description: "Shelly Plus i4 Switch Module"
  friendly_name: "Passage Switch 2"
  api_key: !secret passageswitch2_noise_key
  project_name: "shelly.plusi4-esp32-solo-arduino"
  project_version: "1.0"

packages:
  - !include packages/base/debug.yaml
  - !include packages/devices/switch.shelly-plus-i4.yaml
  - !include packages/common/api.yaml
  - !include packages/common/mqtt.yaml
  - !include packages/common/sensor-die-temp.yaml
  - !include packages/common/button.yaml
  - !include packages/common/text-sensor.yaml
  - !include packages/binary-sensor/shelly-i4-4-buttons-fallback.yaml