substitutions:
  name: bedroom2switch1
  device_ssid: "Bed 2 Switch 1"
  device_description: "Shelly Plus i4 Switch Module"
  friendly_name: "Bedroom 2 Switch 1"
  api_key: !secret bedroom2switch1_noise_key
  project_name: "shelly.plusi4-esp32-solo"
  project_version: "1.0"

packages:
  - !include packages/base/debug.yaml
  - !include packages/devices/switch.shelly-plus-i4.yaml
  - !include packages/common/api.yaml
  - !include packages/common/mqtt.yaml
  - !include packages/common/sensor-die-temp.yaml
  - !include packages/common/button.yaml
  - !include packages/common/text-sensor.yaml
  - !include packages/binary-sensor/shelly-i4-4-buttons-fallback.yaml