substitutions:
  device_ssid: "Living Switch"
  device_name: livingswitch
  device_description: "Shelly Plus i4 Switch Module"
  friendly_name: "Living Switch"
  main_device_id: "livingswitch" # Put the name that you want to see in Home Assistant.
  project_name: "shelly.plusi4-esp32-solo-arduino"
  project_version: "1.0"

<<: !include .base-debug.yaml
<<: !include .base.switch.shelly-plus-i4-arduino.yaml

# Enable Home Assistant API
api:
  password: !secret api_password
  encryption:
    key: !secret livingswitch_noise_key
  reboot_timeout: 0s

<<: !include .base.mqtt-common.yaml
<<: !include .base.sensor-common-die-temp.yaml
<<: !include .base.text-sensor-common.yaml
<<: !include .base.switch-common.yaml
<<: !include .base.binary-sensor-shelly-i4-4-buttons-fallback.yaml