substitutions:
  device_ssid: "Kitchen Dimmer Extra"
  device_name: kitchendimmerextra
  device_description: "Skydance S1-B(WT) Tuya ESP32-C3 Dimmer."
  friendly_name: "Kitchen"    # Put the name that you want to see in Home Assistant.

esphome:
  name: ${device_name}
  comment: ${device_description}
  platformio_options:
    board_build.flash_mode: dio
  # platform: ESP32
  # board: esp32dev

esp32:
  board: esp32-c3-devkitm-1
  framework:
    # type: arduino
    # version: 2.0.2
    # platform_version: 4.3.0
  # framework:
    type: esp-idf

wifi:
    ssid: !secret wifi_all_ssid
    password: !secret wifi_all_password
    # use_address: ashishc3dimmerpilot.local

    # Enable fallback hotspot (captive portal) in case wifi connection fails
    ap:
      ssid: ${device_ssid} Fallback Hotspot
      password: !secret ap_password

# captive_portal:

# Enable logging
# Example configuration entry
debug:

# Logger must be at least debug (default)
logger:
    baud_rate: 0
  
uart:
  - id: tuya1
    rx_pin: GPIO20
    tx_pin: GPIO21
    # baud_rate: 115200
    baud_rate: 9600
    debug:
      direction: BOTH
  # - id: mcu
  #   rx_pin: GPIO20
  #   tx_pin: GPIO21
  #   # baud_rate: 9600
  #   baud_rate: 9600
  #   # stop_bits: 1
  #   debug:
  #     direction: BOTH


# Register the Tuya MCU connection
tuya:
  uart_id: tuya1

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  safe_mode: true
  password: !secret ota_password

# web_server:
#   port: 80

# Sensors with general information.
sensor:
  # WiFi Signal sensor.
  - platform: wifi_signal
    name: ${friendly_name} Signal strength
    update_interval: 60s
    internal: true
    
text_sensor:
  # Expose WiFi information as sensors.
  - platform: wifi_info
    ip_address:
      name: ${friendly_name} IP
    ssid:
      name: ${friendly_name} SSID
    bssid:
      name: ${friendly_name} BSSID
  # Expose Uptime
  - platform: template
    name: ${friendly_name} Uptime
    id: uptime_HA
    icon: mdi:clock-start
    
switch:
    # this provides for a possibility to restart from the web console or Home automation should we ever need it
  - platform: restart
    name: "Restart"
  # - platform: uart
  #   name: "UART String Output"
  #   uart_id: mcu
  #   data: 'DataToSend'
  - platform: uart
    name: "Boot Sequence"
    data: [0x55, 0xAA, 0x00, 0x00, 0x00, 0x00, 0xFF, 0x55, 0xAA, 0x00, 0x01,  0x00, 0x00, 0x00, 0x55, 0xAA, 0x00, 0x02, 0x00, 0x00, 0x01, 0x55, 0xAA, 0x00, 0x03, 0x00, 0x01, 0x03, 0x06, 0x55, 0xAA, 0x00, 0x08, 0x00, 0x00, 0x07, 0x55, 0xAA, 0x00, 0x03, 0x00, 0x01, 0x04, 0x07, 0x55, 0xAA, 0x00, 0x00, 0x00, 0x00, 0xFF]
    uart_id: tuya1
  - platform: uart
    name: "On"
    data: [0x55, 0xAA, 0x00, 0x06, 0x00, 0x05, 0x14, 0x01, 0x00, 0x01, 0x01, 0x21]
    uart_id: tuya1
  - platform: uart
    name: "Off"
    data: [0x55, 0xAA, 0x00, 0x06, 0x00, 0x05, 0x14, 0x01, 0x00, 0x01, 0x00, 0x20]
    uart_id: tuya1
  - platform: uart
    name: "Max"
    data: [0x55, 0xAA, 0x00, 0x06, 0x00, 0x19, 0x1C, 0x03, 0x00, 0x15, 0x31, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x34, 0x30, 0x30, 0x33, 0x65, 0x38, 0x87, 0x55, 0xAA, 0x00, 0x06, 0x00, 0x19, 0x1C, 0x03, 0x00, 0x15, 0x31, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x32, 0x64, 0x36, 0x30, 0x33, 0x65, 0x38, 0xBF, 0x55, 0xAA, 0x00, 0x06, 0x00, 0x08, 0x16, 0x02, 0x00, 0x04, 0x00, 0x00, 0x03, 0xE8, 0x14, 0x55, 0xAA, 0x00, 0x06, 0x00, 0x05, 0x15, 0x04, 0x00, 0x01, 0x00, 0x24, 0x55, 0xAA, 0x00, 0x00, 0x00, 0x00, 0xFF]
    uart_id: tuya1
  - platform: uart
    name: "Min"
    data: [0x55, 0xAA, 0x00, 0x06, 0x00, 0x19, 0x1C, 0x03, 0x00, 0x15, 0x31, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x33, 0x62, 0x30, 0x30, 0x33, 0x65, 0x38, 0xB8, 0x55, 0xAA, 0x00, 0x06, 0x00, 0x19, 0x1C, 0x03, 0x00, 0x15, 0x31, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x31, 0x33, 0x64, 0x30, 0x33, 0x65, 0x38, 0xBB, 0x55, 0xAA, 0x00, 0x06, 0x00, 0x08, 0x16, 0x02, 0x00, 0x04, 0x00, 0x00, 0x00, 0x0A, 0x33, 0x55, 0xAA, 0x00, 0x06, 0x00, 0x05, 0x15, 0x04, 0x00, 0x01, 0x00, 0x24, 0x55, 0xAA, 0x00, 0x00, 0x00, 0x00, 0xFF]
    uart_id: tuya1
  - platform: uart
    name: "Manual Heartbeat"
    data: [0x55, 0xAA, 0x00, 0x00, 0x00, 0x00, 0xFF]
    uart_id: tuya1
  # - platform: uart
  #   name: "MCU Hearbeat"
  #   data: [0xF0]
  #   send_every: 2s
  #   uart_id: mcu
  # - platform: uart
  #   name: "MCU Packet"
  #   data: [0xF8]
  #   uart_id: mcu
  # - platform: template
  #   name: "Heartbeat Switch"
  #   # optimistic: true
  #   turn_on_action:
  #     - uart.write: [0xFF]
  #   turn_off_action:
  #     - uart.write: [0xFF]

#light:
#  - platform: "tuya"
#    name: "${friendly_name}"
#    dimmer_datapoint: 3
#    min_value_datapoint: 2
#    switch_datapoint: 1