substitutions:
  device_ssid: "Kitchen Dimmer"
  device_name: kitchendimmer
  device_description: "Skydance S1-B(WT) Tuya TYWE2S Dimmer."
  friendly_name: "Kitchen"    # Put the name that you want to see in Home Assistant.
  project_name: "skydance.s1-b-wt-dimmer"
  project_version: "1.0"

esphome:
  name: ${device_name}
  comment: ${device_description}
  platform: ESP8266
  board: modwifi
  project:
    name: "${project_name}"
    version: "${project_version}"
  # platformio_options:
  #   board_build.flash_mode: dio
  # platform: ESP32
  # board: esp32dev

# esp32:
#   board: esp32-c3-devkitm-1
#   framework:
#     # type: arduino
#     # version: 2.0.2
#     # platform_version: 4.3.0
#   # framework:
#     type: esp-idf

wifi:
    ssid: !secret wifi_all_ssid
    password: !secret wifi_all_password
    # use_address: kitchendimmerspare.local

    # Enable fallback hotspot (captive portal) in case wifi connection fails
    ap:
      ssid: ${device_ssid} Fallback Hotspot
      password: !secret ap_password

captive_portal:

# Enable logging
# Example configuration entry
debug:

# Logger must be at least debug (default)
logger:
    baud_rate: 0
  
uart:
  - id: softwareforce
    rx_pin: 13
    tx_pin: 15
    baud_rate: 9600
    stop_bits: 1
    debug:
      direction: BOTH
  - id: mcu
    rx_pin: TX
    tx_pin: RX
    baud_rate: 9600
    stop_bits: 1
    debug:
      direction: BOTH
  - id: t
    rx_pin: RX
    tx_pin: TX
    baud_rate: 115200
    stop_bits: 1

# Register the Tuya MCU connection
tuya:
  uart_id: t

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  safe_mode: true
  password: !secret ota_password

web_server:
  port: 80

# Sensors with general information.
sensor:
  # WiFi Signal sensor.
  - platform: wifi_signal
    name: ${friendly_name} Signal strength
    update_interval: 60s
    internal: true
    
text_sensor:
  # Expose WiFi information as sensors.
  - platform: wifi_info
    ip_address:
      name: ${friendly_name} IP
    ssid:
      name: ${friendly_name} SSID
    bssid:
      name: ${friendly_name} BSSID
  # Expose Uptime
  - platform: template
    name: ${friendly_name} Uptime
    id: uptime_HA
    icon: mdi:clock-start
    
switch:
    # this provides for a possibility to restart from the web console or Home automation should we ever need it
  - platform: restart
    name: "Restart"
  - platform: uart
    name: "Boot Sequence"
    data: [0x55, 0xAA, 0x00, 0x00, 0x00, 0x00, 0xFF, 0x55, 0xAA, 0x00, 0x01,  0x00, 0x00, 0x00, 0x55, 0xAA, 0x00, 0x02, 0x00, 0x00, 0x01, 0x55, 0xAA, 0x00, 0x03, 0x00, 0x01, 0x03, 0x06, 0x55, 0xAA, 0x00, 0x08, 0x00, 0x00, 0x07, 0x55, 0xAA, 0x00, 0x03, 0x00, 0x01, 0x04, 0x07, 0x55, 0xAA, 0x00, 0x00, 0x00, 0x00, 0xFF]
    uart_id: t
    # internal: true
  - platform: uart
    name: "On"
    data: [0x55, 0xAA, 0x00, 0x06, 0x00, 0x05, 0x14, 0x01, 0x00, 0x01, 0x01, 0x21]
    uart_id: t
    # internal: true
  - platform: uart
    name: "Off"
    data: [0x55, 0xAA, 0x00, 0x06, 0x00, 0x05, 0x14, 0x01, 0x00, 0x01, 0x00, 0x20]
    uart_id: t
    # internal: true
  - platform: uart
    name: "Max"
    data: [0x55, 0xAA, 0x00, 0x06, 0x00, 0x19, 0x1C, 0x03, 0x00, 0x15, 0x31, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x34, 0x30, 0x30, 0x33, 0x65, 0x38, 0x87, 0x55, 0xAA, 0x00, 0x06, 0x00, 0x19, 0x1C, 0x03, 0x00, 0x15, 0x31, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x32, 0x64, 0x36, 0x30, 0x33, 0x65, 0x38, 0xBF, 0x55, 0xAA, 0x00, 0x06, 0x00, 0x08, 0x16, 0x02, 0x00, 0x04, 0x00, 0x00, 0x03, 0xE8, 0x14, 0x55, 0xAA, 0x00, 0x06, 0x00, 0x05, 0x15, 0x04, 0x00, 0x01, 0x00, 0x24, 0x55, 0xAA, 0x00, 0x00, 0x00, 0x00, 0xFF]
    uart_id: t
    # internal: true
  - platform: uart
    name: "Min"
    data: [0x55, 0xAA, 0x00, 0x06, 0x00, 0x19, 0x1C, 0x03, 0x00, 0x15, 0x31, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x33, 0x62, 0x30, 0x30, 0x33, 0x65, 0x38, 0xB8, 0x55, 0xAA, 0x00, 0x06, 0x00, 0x19, 0x1C, 0x03, 0x00, 0x15, 0x31, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x31, 0x33, 0x64, 0x30, 0x33, 0x65, 0x38, 0xBB, 0x55, 0xAA, 0x00, 0x06, 0x00, 0x08, 0x16, 0x02, 0x00, 0x04, 0x00, 0x00, 0x00, 0x0A, 0x33, 0x55, 0xAA, 0x00, 0x06, 0x00, 0x05, 0x15, 0x04, 0x00, 0x01, 0x00, 0x24, 0x55, 0xAA, 0x00, 0x00, 0x00, 0x00, 0xFF]
    uart_id: t
    # internal: true
  - platform: uart
    name: "Manual Heartbeat"
    data: [0x55, 0xAA, 0x00, 0x00, 0x00, 0x00, 0xFF]
    uart_id: t
    # internal: true
  - platform: uart
    name: "dodgy packet"
    data: [0x0F]
    uart_id: mcu
    # internal: true

light:
  - platform: "tuya"
    name: "${friendly_name}"
    dimmer_datapoint: 22
    # min_value_datapoint: 26
    switch_datapoint: 20
    min_value: 25
    max_value: 1000
# Datapoint 20: switch (value: ON)
# Datapoint 21: enum (value: 0)
# Datapoint 22: int value (value: 878)
# Datapoint 26: int value (value: 0)
# Product: '{"p":"vhqbpwy6a5ke1nig","
# Backlog TuyaMCU 11,20; TuyaMCU 21,22; DimmerRange 10,1000