esphome:
  name: wb5c3
#   # platformio_options:
#   #   platform_packages:
#   #     - framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#2.0.0
#   #   platform:
#   #     - https://github.com/platformio/platform-espressif32.git#feature/arduino-upstream

# # Example configuration entry
# esp32:
#   # board: esp32-c3-devkitm-1
#   # framework:
#   #   type: arduino
#   #   version: latest
#   board: esp32-c3-devkitm-1
#   framework:
#   #   type: esp-idf
#   # currently needed, but not in the future
#     type: arduino
#     version: latest
#   variant: ESP32C3
# compiles below
  # platformio_options:
  #   platform: https://github.com/platformio/platform-espressif32.git#feature/arduino-upstream
  #   platform_packages:
  #     - framework-arduinoespressif32@https://github.com/espressif/arduino-esp32.git#2.0.0
  #   board_build.variant: esp32c3
  #   board_build.f_cpu: 160000000L
  #   board_build.f_flash: 40000000L
  #   upload_protocol: esptool
  #   board_build.flash_mode: dio

esp32:
  board: esp32-c3-devkitm-1
  framework:
    # type: arduino
    # version: 2.0.2
    # version: dev
    type: esp-idf
  variant: ESP32C3

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:

ota:
  password: "0499bd6320fa6677cb9f637412957e5d"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Wb5C3 Fallback Hotspot"
    password: "3W0VdNDS5bJe"

# captive_portal:
