binary_sensor:
  - platform: status
    name: "${friendly_name} Status"
  - platform: gpio
    pin:
      number: GPIO13
      #mode: INPUT_PULLUP
      #inverted: True
    name: "${friendly_name} Switch 1"
    on_state:
      then:
        - if:
            condition:
              api.connected:
            then:
              - homeassistant.event:
                  event: esphome.${name}
                  data:
                    title: button 1 short click            
            else:
              - mqtt.publish:
                  topic: ${name}/button/1/command
                  payload: "SHORT_CLICK"
    internal: true
    id: switchid1
  # - platform: gpio
  #   pin:
  #     number: GPIO5
  #     #mode: INPUT_PULLUP
  #     #inverted: True
  #   name: "${name} Switch 2"
  #   on_state:
  #     then:
  #       - light.toggle: lightid2
  #   internal: true
  #   id: switchid2