binary_sensor:
  - platform: status
    name: "${friendly_name} Status"
  - platform: gpio
    name: "${friendly_name} Button 1"
    pin:
      number: GPIO10
      mode:
        input: true
    on_multi_click:
      - timing:
          - ON for at most 0.9s
          - OFF for at least 0.1s
        then:
            # http request post
            # - http_request.post: http://${remote_node}/light/${remote_light_id}/toggle
            - http_request.post: 
                url: http://ashishspot1.local/light/ashish_spot_1/toggle
                #headers: 
                #  Content-Type: application/json
                #  Authentication: Basic "${http_auth}
                # verify_ssl: False
    # on_release:
    #   - homeassistant.event:
    #       event: esphome.${name}
    #       data:
    #         title: button 1 released
    internal: true
    id: button1
    filters:
      - delayed_on_off: 50ms