# Example configuration entry
udp:
  - id: udp_internal
  - id: udp_external
    port:
      listen_port: 18511
      broadcast_port: 18512
    # encryption: "${udp_consumer_key_1}"
    # ping_pong_enable: true
    # rolling_code_enable: true
    addresses:
      - "${external_udp_ip}"
      # providers:
      #   - name: "${udp_provider_device_name_1}"
      #     encryption: "${udp_provider_key_1}"
      # sensors:
      #   - id: uptime_sensor

packet_transport:
  - id: transport_internal
    platform: udp
    udp_id: udp_internal
    update_interval: 10s

binary_sensor:
  - platform: packet_transport
    provider: "${udp_provider_device_name_1}"
    id: "${external_presence_sensor_id}"
    # --- Automation when Sensor turns ON ---
    # Proper state change triggers
    on_state:
      - if:
          condition:
            # and:
              # - not:
              #     api.connected:
              # - not:
              #     mqtt.connected:
            - binary_sensor.is_on: "${external_presence_sensor_id}"
          then:
            - light.turn_on: "${device_id_white}"
          else:
            - light.turn_off: "${device_id_white}"