# Enable logging
# Logger must be at least debug (default)
logger:
  baud_rate: 0

ota:
  - platform: esphome
    version: 2
    password: !secret ota_password

safe_mode:

# wifi:
#     ssid: !secret wifi_all_ssid
#     password: !secret wifi_all_password

#     # Enable fallback hotspot (captive portal) in case wifi connection fails
#     ap:
#       ssid: ${device_ssid} Fallback Hotspot
#       password: !secret ap_password
#     power_save_mode: none

network:
    enable_ipv6: true
    min_ipv6_addr_count: 2