# Device Specific Config
esphome:
  name: "${name}"
  comment: ${device_description}
  platformio_options:
    board_build.flash_mode: dio
    upload_speed: 921600

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

external_components:
  - source: github://jesserockz/wizmote-esphome
    components:
      - esp_now
      - wizmote

esp_now:

wizmote:
  on_button:
    if:
      condition:
        lambda: return data.button >= 16 && data.button <= 19;
      then:
        - homeassistant.event:
            event: esphome.wizmote_choose
            data:
              mac: !lambda "return format_hex(data.bssid, 6);"
              button: !lambda "return data.button - 15;"
              sequence: !lambda "return data.sequence;"
      else:
        - homeassistant.event:
            event: esphome.wizmote_action
            data:
              mac: !lambda "return format_hex(data.bssid, 6);"
              button: !lambda "return data.button;"
              sequence: !lambda "return data.sequence;"

captive_portal:

web_server:
  port: 80
  auth:
    username: admin
    password: !secret web_server_password
  include_internal: true
  local: true

output:
  - platform: ledc
    id: output_red
    pin: GPIO3
    frequency: 16000Hz
  - platform: ledc
    id: output_green
    pin: GPIO10
    frequency: 16000Hz
  - platform: ledc
    id: output_blue
    pin: GPIO7
    frequency: 16000Hz
  - platform: ledc
    id: output_cold_white
    pin: GPIO6
    max_power: 80%
    frequency: 16000Hz
  - platform: ledc
    id: output_warm_white
    pin: GPIO5
    max_power: 80%
    frequency: 16000Hz

light:
  - platform: cwww
    name: ${friendly_name}
    id: ${device_id_white}
    cold_white: output_cold_white
    warm_white: output_warm_white
    cold_white_color_temperature: 6536 K
    warm_white_color_temperature: 2000 K
    constant_brightness: false
    gamma_correct: 0
    default_transition_length: 1s
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - globals.set:
          id: last_light_on
          value: "1"
    icon: "hue:ceiling-aurelle-circle"
  - platform: rgb
    name: ${friendly_name_rgb}
    id: ${rgb_device_id}
    red: output_red
    green: output_green
    blue: output_blue
    default_transition_length: 0.5s
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - globals.set:
          id: last_light_on
          value: "2"
    icon: "hue:ceiling-aurelle-circle"
# Device configuration, as extracted from Tuya:
# - LED Cool (Channel 4) on P6
# - LED Blue (Channel 3) on P9
# - PWM Frequency 16000
# - LED Red (Channel 1) on P7
# - LED Warm (Channel 5) on P24
# Device seems to be using CB3L module, which is using BK7231N.
# And the Tuya section starts, as usual, at 2023424

# ESP8685-WROOM-04
# Cool is GPIO6
# Blue is GPIO7
# PWM Frequency 16000
# Red is GPIO3
# Warm is GPIO5
# Green is GPIO10
