esphome:
  name: ${name}
  comment: ${device_description}
  project:
    name: "${project_name}"
    version: "${project_version}"

esp32:
  board: esp32dev
  framework: 
    type: arduino

safe_mode:

wifi:
    ssid: !secret wifi_all_ssid
    password: !secret wifi_all_password
    # use_address: passagelight.local

    # Enable fallback hotspot (captive portal) in case wifi connection fails
    ap:
      ssid: ${device_ssid}
      password: !secret ap_password

network:
    enable_ipv6: true
    min_ipv6_addr_count: 2

captive_portal:

web_server:
  port: 80
  auth:
    username: admin
    password: !secret web_server_password
  include_internal: true
  # local: true

output:
  - platform: ledc
    id: output_red
    pin: GPIO25 # 25
    # max_power: 100%
    frequency: ${frequency_rgb}
  - platform: ledc
    id: output_green
    pin: GPIO26 # 26
    # max_power: 100%
    frequency: ${frequency_rgb}
  - platform: ledc
    id: output_blue
    pin: GPIO27 # 27
    # max_power: 100%
    frequency: ${frequency_rgb}
  - platform: ledc
    id: output_cold_white
    max_power: 100%
    frequency: ${frequency_cw}
    pin: GPIO4 # 4
  - platform: ledc
    id: output_warm_white
    pin: GPIO2 # 2
    max_power: 100%
    frequency: ${frequency_ww}

light:
  - platform: cwww
    name: ${device_name_white}    # Put the name that you want to see in Home Assistant.
    id: ${device_id_white}    # id used in esphome.
    cold_white: output_cold_white
    warm_white: output_warm_white
    cold_white_color_temperature: 6536 K
    warm_white_color_temperature: 2000 K
    constant_brightness: false
    gamma_correct: 0
    default_transition_length: 1s
    on_turn_on:
    - globals.set:
        id: last_light_on
        value: '1'
    icon: "hue:ceiling-aurelle-circle"
  - platform: rgb
    name: ${device_name_rgb}
    id: ${device_id_rgb}
    red: output_red
    green: output_green
    blue: output_blue
    default_transition_length: 0.5s
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
    - globals.set:
        id: last_light_on
        value: '2'
    icon: "hue:ceiling-aurelle-circle"