# Device Specific Config
esphome:
  name: ${name}
  comment: ${device_description}
  project:
    name: "${project_name}"
    version: "${project_version}"
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino
#    version: 2.0.5
#    platform_version: 5.2.0

# external_components:
#   - source: github://pr#3820
#     components: [ ledc ]

external_components:
  - source:
      type: local
      path: my_external_components/tuya_commit_2_tuya_core_2_version_handling
      # path: my_external_components/tuya_commit_1_tuya_core

captive_portal:

web_server:
  port: 80
  auth:
    username: admin
    password: !secret web_server_password
  include_internal: true
  local: true

uart:
  - id: mcu
    rx_pin: GPIO20
    tx_pin: GPIO21
    # baud_rate: 9600
    baud_rate: 115200
    rx_buffer_size: 1024
    debug:
      direction: BOTH
      dummy_receiver: false
      sequence:
        - lambda: UARTDebug::log_hex(direction, bytes, ':');
      after:
        bytes: 150
        timeout: 100ms

# # Register the Tuya MCU connection
# tuya:
#   uart_id: mcu

tuya:
  # standard_trace_mode: true
  # raw_trace_mode: true
  # compatibility_mode:
  #   handle_historical_records: true
  #   # DO NOT enable force_low_power or ignore_init here
  #   # as the ZY-M100 needs the full handshake to function correctly.

  # on_datapoint_update:
  #   - sensor_datapoint: 1  # Standard Presence DP for many sensors
  #     datapoint_type: bool
  #     then:
  #       - logger.log: "Testing my new on_datapoint_update hook!"

number:
  - platform: "tuya"
    name: "${friendly_name} Sensitivity"
    number_datapoint: 2
    min_value: 0
    max_value: 9
    step: 1
    icon: "mdi:ray-vertex"
  - platform: "tuya"
    name: "${friendly_name} Near Detection"
    number_datapoint: 3
    min_value: 0
    max_value: 1000
    step: 1
    mode: slider
    # filters:
    #   - multiply: 0.01
    unit_of_measurement: "cm"
    icon: "mdi:signal-distance-variant"
    # device_class: "distance"
    # state_class: "measurement"
  - platform: "tuya"
    name: "${friendly_name} Far Detection"
    number_datapoint: 4
    min_value: 0
    max_value: 1000
    step: 1
    mode: slider
    unit_of_measurement: "cm"
    icon: "mdi:signal-distance-variant"
    # device_class: "distance"
    # state_class: "measurement"
  # - platform: "tuya"
  #   name: "Target Distance"
  #   number_datapoint: 9
  #   min_value: 0
  #   max_value: 1000
  #   step: 1
  #   unit_of_measurement: "cm"
  #   icon: "mdi:eye"
  # device_class: "distance"
  # state_class: "measurement"
  - platform: "tuya"
    name: "${friendly_name} Detection Delay"
    number_datapoint: 101
    min_value: 0
    max_value: 100
    step: 1
    unit_of_measurement: "s"
    mode: slider
    icon: "mdi:clock"
    # device_class: "duration"
    # state_class: "measurement"
  - platform: "tuya"
    name: "${friendly_name} Fading Time"
    number_datapoint: 102
    min_value: 0
    max_value: 1500
    step: 1
    unit_of_measurement: "s"
    mode: slider
    icon: "mdi:clock"
    # device_class: "duration"
    # state_class: "measurement"

  # - platform: "tuya"
  #   name: "Self Check Result"
  #   sensor_datapoint: 6
  #   icon: mdi:eye
  #   filters:
  #   - substitute:
  #     - "0 -> Checking"
  #     - "1 -> Check Success"
  #     - "2 -> Check Failure"
  #     - "3 -> Others"
  #     - "4 -> Comm Fault"
  #     - "5 -> Radar Fault"
  # - platform: template
  #   name: "${friendly_name} Self Check Result"
  #   icon: mdi:eye
  #   lambda: |-
  #     if (id(selfcheck).state == 0) {
  #       return {"Checking"};
  #     }
  #     else if (id(selfcheck).state == 1) {
  #       return {"Check Success"};
  #     }
  #     else if (id(selfcheck).state == 2) {
  #       return {"Check Failure"};
  #     }
  #     else if (id(selfcheck).state == 3) {
  #       return {"Others"};
  #     }
  #     else if (id(selfcheck).state == 4) {
  #       return {"Comm Fault"};
  #     }
  #     else if (id(selfcheck).state == 5) {
  #       return {"Radar Fault"};
  #     }
  #     else return {"Unknown"};

select:
  - platform: "tuya"
    # tuya_id: "mcu"
    name: "${friendly_name} Self Check Result"
    icon: mdi:eye
    enum_datapoint: 6
    options:
      0: Checking
      1: Check Success
      2: Check Failure
      3: Others
      4: Comm Fault
      5: Radar Fault
