# Device Specific Config
esphome:
  name: ${name}
  comment: ${device_description}
  platformio_options:
    board_build.flash_mode: dio
    # needed for when board: um_tinys3 is set
    board_build.extra_flags:
      - "-DARDUINO_USB_CDC_ON_BOOT=0"  # Override, defaults to '-DARDUINO_USB_CDC_ON_BOOT=1'
  project:
    name: "${project_name}"
    version: "${project_version}"

esp32:
  # board: um_tinys3, has OTA issues using generic instead
  # board: um_tinys3
  # fallback generic board, known to work for all and OTA
  board: esp32-s3-devkitc-1
  variant: esp32s3
  # framework test setting, worked but OTA broken
  # framework:
  #   type: arduino
  #   version: dev
  #   platform_version: ^5.1.1
  # fallback config, known to work for all and OTA
  # framework:
  #   type: arduino
  #   platform_version: 5.2.0
  # testing, should work nicely
  framework:
    type: arduino
    # version: 2.0.5
    platform_version: 5.2.0

# external_components:
#   - source:
#       type: local
#       path: my_external_components/tuya_cover_custom

captive_portal:

web_server:
  port: 80
  auth:
    username: admin
    password: !secret web_server_password
  include_internal: true
  local: true

# Old Config had TuyaMCU connection Issues

# uart:
#     rx_pin: GPIO6
#     tx_pin: GPIO7
#     baud_rate: 9600
#     debug:
#       direction: BOTH
#       dummy_receiver: false
#       sequence:
#         - lambda: UARTDebug::log_hex(direction, bytes, ':');

uart:
    rx_pin: GPIO6
    tx_pin: GPIO7
    baud_rate: 9600
    debug:
      direction: BOTH
      dummy_receiver: false
      sequence:
        - lambda: UARTDebug::log_hex(direction, bytes, ':');

# Register the Tuya MCU connection
# tuya:
tuya:

cover:
  - platform: "tuya"
    id: "${device_id_white}"
    name: "${cover_name}"
    control_datapoint: 1
    position_datapoint: 2
    position_report_datapoint: 3
    direction_datapoint: 5
    invert_position: true
    device_class: blind

