binary_sensor:
  - platform: status
    name: "${friendly_name} Status"
  # - platform: "tuya"
  #   name: "${friendly_name} Switch Mode"
  #   sensor_datapoint: 102
  # - platform: "tuya"
  #   name: "${friendly_name} Tuya Test"
  #   sensor_datapoint: 104