esphome:
  name: ${name}
  comment: ${device_description}
  platformio_options:
    board_build.flash_mode: dio
  project:
    name: "${project_name}"
    version: "${project_version}"

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino
#    version: 2.0.5
#    platform_version: 5.2.0

external_components:
  - source: github://pr#3820
    components: [ ledc ]

captive_portal:

web_server:
  port: 80
  auth:
    username: admin
    password: !secret web_server_password
  include_internal: true
  # local: true

output:
  - platform: ledc
    id: output_cold_white
    pin: GPIO4
  - platform: ledc
    id: output_warm_white
    pin: GPIO5

light:
  - platform: cwww
    name: ${friendly_name}
    id: ${device_id_white}
    cold_white: output_cold_white
    warm_white: output_warm_white
    cold_white_color_temperature: 6536 K
    warm_white_color_temperature: 2000 K
    constant_brightness: false
    gamma_correct: 0
    default_transition_length: 1s
    icon: "hue:ceiling-aurelle-circle"