# Device Specific Config
esphome:
  name: "${name}"
  comment: ${device_description}
  platformio_options:
    board_build.flash_mode: dio
    upload_speed: 921600
    
esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

external_components:
  - source: github://pr#3820
    components: [ ledc ]
  - source:
      type: git
      url: https://github.com/KaufHA/common
    components: [ ddp ]
    refresh: always

captive_portal:

web_server:
  port: 80
  auth:
    username: admin
    password: !secret web_server_password
  include_internal: true
  local: true

output:
  - platform: ledc
    id: output_red
    pin: GPIO6
    # max_power: 100%
    # frequency: ${frequency_rgb}
  - platform: ledc
    id: output_green
    pin: GPIO7
    # max_power: 100%
    # frequency: ${frequency_rgb}
  - platform: ledc
    id: output_blue
    pin: GPIO3
    # max_power: 100%
    # frequency: ${frequency_rgb}
  - platform: ledc
    id: output_cold_white
    pin: GPIO5
    max_power: 100%
    # frequency: ${frequency_cw}
  - platform: ledc
    id: output_warm_white
    pin: GPIO4
    max_power: 100%
    # frequency: ${frequency_ww}

e131:
  method: multicast # default: register E1.31 to Multicast group

ddp:

light:
  - platform: cwww
    name: ${device_name_white}
    id: ${device_id_white}
    cold_white: output_cold_white
    warm_white: output_warm_white
    cold_white_color_temperature: 6536 K
    warm_white_color_temperature: 2000 K
    constant_brightness: false
    gamma_correct: 0
    default_transition_length: 1s
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
    - globals.set:
        id: last_light_on
        value: '1'
    icon: ${light_icon}
  - platform: rgb
    name: ${device_name_rgb}
    id: internal_rgb
    red: output_red
    green: output_green
    blue: output_blue
    restore_mode: RESTORE_DEFAULT_OFF
    internal: true
  - platform: partition
    name: ${device_name_rgb}
    id: ${device_id_rgb}
    segments:
      # Use internal_rgb as a single light partition for WLED and e1.31
      - single_light_id: internal_rgb
    default_transition_length: 0.25s
    on_turn_on:
    - light.turn_off: ${device_id_white}
    - globals.set:
        id: last_light_on
        value: '2'
    icon: "${light_icon_2}"
    effects:
      - ddp
      - e131:
          universe: 1
          channels: RGB
      