switch:
    # this provides for a possibility to restart from the web console or Home automation should we ever need it
  - platform: restart
    id: restart_switch
    name: "${friendly_name} Restart"
  - platform: safe_mode
    name: "${friendly_name} Restart (Safe Mode)"
  - platform: uart
    name: "Heartbeat"
    # 55 AA 00 00 00 00 FF
    data: [0x55, 0xAA, 0x00, 0x00, 0x00, 0x00, 0xFF]
    internal: true
  - platform: uart
    name: "Product Information"
    # 55 AA 00 01 00 00 00
    data: [0x55, 0xAA, 0x00, 0x01, 0x00, 0x00, 0x00]
    internal: true
  - platform: uart
    name: "Working Mode"
    # 55 AA 00 02 00 00 01
    data: [0x55, 0xAA, 0x00, 0x02, 0x00, 0x00, 0x01]
    internal: true
  - platform: uart
    name: "Status"
    # 55 AA 00 08 00 00 07
    data: [0x55, 0xAA, 0x00, 0x08, 0x00, 0x00, 0x07]
    internal: true
  - platform: uart
    name: "Normal DP1 - DPID5"
    # 55 AA 00 06 00 05 05 01 00 01 00 11
    # query
    # 0x55 0xAA 0x00 0x08 0x00 0x00 0x07
    # 0x55, 0xAA, 0x00, 0x06, 0x00, 0x05, 0x05, 0x01, 0x00, 0x01, 0x00, 0x11
    data: [0x55, 0xAA, 0x00, 0x06, 0x00, 0x05, 0x05, 0x01, 0x00, 0x01, 0x00, 0x11]
    internal: true
  - platform: uart
    name: "Reverse DP1 - DPID5"
    data: [0x55, 0xAA, 0x00, 0x06, 0x00, 0x05, 0x05, 0x01, 0x00, 0x01, 0x00, 0x12]
    internal: true
  - platform: uart
    name: "Normal DP2 - DPID103"
    data: [0x55, 0xAA, 0x00, 0x06, 0x00, 0x05, 0x05, 0x01, 0x00, 0x01, 0x00, 0x11]
    # internal: true
  - platform: uart
    name: "Reverse DP2 - DPID103"
    data: [0x55, 0xAA, 0x00, 0x06, 0x00, 0x05, 0x05, 0x01, 0x00, 0x01, 0x00, 0x11]
    # internal: true
  - platform: uart
    name: "Normal DP3 - DPID101"
    data: [0x55, 0xAA, 0x00, 0x06, 0x00, 0x05, 0x05, 0x01, 0x00, 0x01, 0x00, 0x11]
    internal: true
  - platform: uart
    name: "Reverse DP3 - DPID101"
    data: [0x55, 0xAA, 0x00, 0x06, 0x00, 0x05, 0x05, 0x01, 0x00, 0x01, 0x00, 0x11]
    internal: true
  - platform: uart
    name: "Normal DP4 - DPID102"
    data: [0x55, 0xAA, 0x00, 0x06, 0x00, 0x05, 0x05, 0x01, 0x00, 0x01, 0x00, 0x11]
    internal: true
  - platform: uart
    name: "Reverse DP4 - DPID102"
    data: [0x55, 0xAA, 0x00, 0x06, 0x00, 0x05, 0x05, 0x01, 0x00, 0x01, 0x00, 0x11]
    internal: true
  - platform: uart
    name: "Normal DP5 - DPID104"
    data: [0x55, 0xAA, 0x00, 0x06, 0x00, 0x05, 0x05, 0x01, 0x00, 0x01, 0x00, 0x11]
    internal: true
  - platform: uart
    name: "Reverse DP5 - DPID104"
    data: [0x55, 0xAA, 0x00, 0x06, 0x00, 0x05, 0x05, 0x01, 0x00, 0x01, 0x00, 0x11]
    internal: true
  - platform: uart
    name: "Normal DP6 - DPID105"
    data: [0x55, 0xAA, 0x00, 0x06, 0x00, 0x05, 0x05, 0x01, 0x00, 0x01, 0x00, 0x11]
    internal: true
  - platform: uart
    name: "Reverse DP6 - DPID105"
    data: [0x55, 0xAA, 0x00, 0x06, 0x00, 0x05, 0x05, 0x01, 0x00, 0x01, 0x00, 0x11]
    internal: true
  - platform: uart
    name: "Normal DP7 - DPID106"
    data: [0x55, 0xAA, 0x00, 0x06, 0x00, 0x05, 0x05, 0x01, 0x00, 0x01, 0x00, 0x11]
    internal: true
  - platform: uart
    name: "Reverse DP7 - DPID106"
    data: [0x55, 0xAA, 0x00, 0x06, 0x00, 0x05, 0x05, 0x01, 0x00, 0x01, 0x00, 0x11]
    internal: true
  - platform: uart
    name: "Normal DP8 - DPID100"
    data: [0x55, 0xAA, 0x00, 0x06, 0x00, 0x05, 0x05, 0x01, 0x00, 0x01, 0x00, 0x11]
    internal: true
  - platform: uart
    name: "Reverse DP8 - DPID100"
    data: [0x55, 0xAA, 0x00, 0x06, 0x00, 0x05, 0x05, 0x01, 0x00, 0x01, 0x00, 0x11]
    internal: true
  - platform: uart
    name: "Normal DP9 - DPID107"
    data: [0x55, 0xAA, 0x00, 0x06, 0x00, 0x05, 0x05, 0x01, 0x00, 0x01, 0x00, 0x11]
    internal: true
  - platform: uart
    name: "Reverse DP9 - DPID107"
    data: [0x55, 0xAA, 0x00, 0x06, 0x00, 0x05, 0x05, 0x01, 0x00, 0x01, 0x00, 0x11]
    internal: true