# Device Specific Config
esphome:
  name: "${name}"
  comment: ${device_description}
  platformio_options:
    board_build.flash_mode: dio
    upload_speed: 921600
    # platform: espressif32@5.2.0
  # includes:
  #   - .esp32-internal-temperature.h
    
esp32:
  board: esp32-c3-devkitm-1
  framework: 
    type: arduino
#    version: 2.0.5
#    platform_version: 5.2.0
# framework:
#   type: esp-idf

external_components:
  - source: github://pr#3820
    components: [ ledc ]
  - source:
      type: git
      url: https://github.com/KaufHA/common
    components: [ ddp ]
    refresh: always

captive_portal:

web_server:
  port: 80
  auth:
    username: admin
    password: !secret web_server_password
  include_internal: true
  local: true

output:
  - platform: ledc
    id: output_red
    pin: GPIO4
    # max_power: 100%
    # frequency: ${frequency_rgb} GPIO4 - RED
  - platform: ledc
    id: output_green
    pin: GPIO5
    # max_power: 100%
    # frequency: ${frequency_rgb} GPIO5 - GREEN
  - platform: ledc
    id: output_blue
    pin: GPIO6
    # max_power: 100%
    # frequency: ${frequency_rgb} GPIO6 - BLUE
  - platform: ledc
    id: output_cold_white
    pin: GPIO3
    max_power: 100%
    # frequency: ${frequency_cw} GPIO3 - COLD WHITE
  - platform: ledc
    id: output_warm_white
    pin: GPIO7
    max_power: 100%
    # frequency: ${frequency_ww} GPIO7 - WARM WHITE

ddp:

light:
  - platform: cwww
    name: ${device_name_white}
    id: ${device_id_white}
    cold_white: output_cold_white
    warm_white: output_warm_white
    cold_white_color_temperature: 6536 K
    warm_white_color_temperature: 2000 K
    constant_brightness: false
    gamma_correct: 0
    default_transition_length: 1s
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
    - globals.set:
        id: last_light_on
        value: '1'
    icon: ${light_icon}
  - platform: rgb
    name: ${device_name_rgb}
    id: ${device_id_rgb}
    red: output_red
    green: output_green
    blue: output_blue
    default_transition_length: 0.25s
    on_turn_on:
    - light.turn_off: ${device_id_white}
    - globals.set:
        id: last_light_on
        value: '2'
    icon: "${light_icon_2}"
    effects:
      - ddp:
          name: DDP
          timeout: 10s
          disable_gamma: true
          brightness_scaling: none
      # - wled:
      #     # port: 21324
      # - e131:
      #     universe: 1
      #     channels: RGB
      