esphome:
  name: t
  friendly_name: T

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "tZE5El/Zg0tGr4DTsBA3G4Yq4QF/IcLisM36aUnTy1I="

ota:
  - platform: esphome
    password: "b0e604e45ee5155712c08fec317a5756"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "T Fallback Hotspot"
    password: "OwI3rBvsjuYO"

captive_portal:
    